### ISSUE TITLE
Create maven artifact

### ISSUE THREAD

**Issue by DoubleMalt** [seancfoley/IPAddress#1]
This library would be great if id would be in the maven registry

**Comment by seancfoley** [comment]
Hi,  I've never been a maven user but heard only good things about it.  Any suggestions where to start on that?

**Comment by RomanSyroeshko** [comment]
Any news?

**Comment by seancfoley** [comment]
Hello, 

The library is now available from the maven central repository.

The code that is currently in the master branch was recently branched as version 2.0.0 and that is the release in maven (there will be a version 3 in a few weeks).
<groupId>com.github.seancfoley</groupId>
 <artifactId>ipaddress</artifactId>
<version>2.0.0</version>

https://repo1.maven.org/maven2/com/github/seancfoley/ipaddress/2.0.0/

I've tried it out as a dependency in an eclipse maven project, and it appears to be fine.  Requires Java 8.  There is a version 1.0.0 that can be used with Java 7 which I will probably eventually get into maven as well.
