### ISSUE TITLE
Some ideas about trie trees

### ISSUE THREAD

**Issue by chentyhehe** [seancfoley/IPAddress#108]
In the process of using AssociativeAddressTrie, I found out that when constructing the trie tree, the value of the latter of the same ip will overwrite the former, ip is not exactly the same but there is an intersection then both ip will exist in the tree, corresponding to a different value, but there is an overlap between these two ip addresses, so I wondered if it is possible to provide an extension in the building the trie tree to deal with conflicting ip addresses and provide an extension to the processing of value values, such as merge, append, etc. The main reason for this question is that the trie tree seems to only provide a query capability, and does not provide a way to deal with ip conflicts, so there seems to be no high-performance way to query a single ip to find out all the values that contain that ip.

**Comment by seancfoley** [comment]
If two ips are exactly the same, then yes, like any other map, setting the value for one overwrites the value for the other, since they are the same.  That's how maps work, that's how lookups work.  The idea you could have two identical keys mapping to different values, that simply cannot work.  You'd need to use a different data structure, like an array.  Or just create different keys with java.util.TreeMap.

It is possible to combine the values though, that is what [remap](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/format/util/AssociativeAddressTrie.html#remap-K-java.util.function.Function-) is for.

**Comment by seancfoley** [comment]
Example:
```java
public class Code {
	public static void main(String[] args) {
		IPv4AddressAssociativeTrie<Objs> trie = construct();
		System.out.println("1.1.1.1 is associated with " + 
			associatedObjects(trie, getAddr("1.1.1.1")));
	}
	
	static class Objs {
		Set<Object> objs = new HashSet<>();
		
		public String toString() {
			return objs.toString();
		}
	}
	
	static IPv4AddressAssociativeTrie<Objs> construct()  {
		IPv4AddressAssociativeTrie<Objs> trie = new IPv4AddressAssociativeTrie<>();
		Object object1 = new Object() {
			public String toString() {
				return "object1";
			}
		};
		associate(trie, getAddr("1.1.1.1"), object1);
		
		Object object2 = new Object() {
			public String toString() {
				return "object2";
			}
		};
		associate(trie, getAddr("1.1.1.1"), object2);
		
		System.out.println(trie);
		
		return trie;
	}
	
	static IPv4Address getAddr(String addrStr) {
		return new IPAddressString(addrStr).getAddress().toIPv4();
	}
	
	static <K extends IPAddress> void associate(AssociativeAddressTrie<K, Objs> trie, 
			K addr, Object obj)   {
		trie.remap(addr, objs -> {
			if(objs == null) {
				objs = new Objs();
			}
			objs.objs.add(obj);
			return objs;
		});
	}
	
	static <K extends IPAddress> Set<Object> associatedObjects( 
			AssociativeAddressTrie<K, Objs> trie, K addr)  {
		AssociativeTrieNode<K, Objs> containing = trie.elementsContaining(addr);
		Set<Object> result = new HashSet<>();
		if(containing != null) {
			do {
				result.addAll(containing.getValue().objs);
				AssociativeTrieNode<K, Objs> next = containing.getLowerSubNode();
				if(next == null) {
					next = containing.getUpperSubNode();
				}
				containing = next;
			} while(containing != null);
		}
		return result;
	}
}
```
Output:
```
○ 0.0.0.0/0 (1)
└─● 1.1.1.1 = [object1, object2] (1)

1.1.1.1 is associated with [object1, object2]
```
Note that this is exactly the same trie code as in the answer to https://github.com/seancfoley/IPAddress/issues/107
