### ISSUE TITLE
it converted a err cidr when start ip equals end ip or cidr contains a single Ip

### ISSUE THREAD

**Issue by lwpk110** [seancfoley/IPAddress#11]
for example:
```
public static List<String> rangeToCIDR(String start, String end) {
        IPAddressString startIpAddressString = new IPAddressString(start);
        IPAddressString endIpAddressString = new IPAddressString(end);
        IPAddress startIpAddress = startIpAddressString.getAddress();
        IPAddress endIpAddress = endIpAddressString.getAddress();
        IPAddressSeqRange range = startIpAddress.toSequentialRange(endIpAddress);
        IPAddress[] result = range.spanWithPrefixBlocks();
        return Arrays.stream(result).map(Address::toString).collect(Collectors.toList()).toString();
}
```
examp1:
> start ip: 77.220.115.0
> end id: 77.220.115.0
when test, it shows  [77.220.115.0], but correct result is [77.220.115.0/32]

exmap2
> start ip: 77.220.115.0
> end id: 77.220.116.64
when test, it shows  [77.220.115.0/24, 77.220.116.0/26, 77.220.116.64], but correct result is [77.220.115.0/24, 77.220.116.0/26, 77.220.116.64/32];

is it a bug? thks

**Comment by seancfoley** [comment]
Looks like it is dropping the prefix length (32) when it is just a single address (when prefix length is the full address length).  I don't think I would consider this a bug, since 77.220.115.0 and 77.220.115.0/32 are more or less the same thing (a single address 77.220.115.0), albeit perhaps there are cases where preserving the prefix length makes sense.  I will give this a bit of thought, maybe for consistency it is better to add the bit length prefix length.

**Comment by seancfoley** [comment]
I'm thinking it might make sense to return addresses with prefix length as you are suggesting, but that would be in a future release.

However, in the meantime you can just use either IPAddress::assignPrefixForSingleBlock or IPAddress::assignMinPrefixForBlock to achieve the same result as shown:

    public static List<String> rangeToCIDR(String start, String end) {
	 	IPAddressString startIpAddressString = new IPAddressString(start);
	        IPAddressString endIpAddressString = new IPAddressString(end);
	        IPAddress startIpAddress = startIpAddressString.getAddress();
	        IPAddress endIpAddress = endIpAddressString.getAddress();
	        IPAddressSeqRange range = startIpAddress.toSequentialRange(endIpAddress);
	        IPAddress[] result = range.spanWithPrefixBlocks();
	       // return Arrays.stream(result).map(IPAddress::assignPrefixForSingleBlock).map(Address::toString).collect(Collectors.toList());
	        return Arrays.stream(result).map(IPAddress::assignMinPrefixForBlock).map(Address::toString).collect(Collectors.toList());
	 }
	
		
	public static void main(String args[]) {
		List<String> strs = rangeToCIDR("77.220.115.0", "77.220.115.0");
		System.out.println(strs.toString());
			
		strs = rangeToCIDR("77.220.115.0", "77.220.116.64");
		System.out.println(strs.toString());
	}

Result:

    [77.220.115.0/32]
    [77.220.115.0/24, 77.220.116.0/26, 77.220.116.64/32]
