### ISSUE TITLE
Loop through IPAddress list that contains both v4 and v6

### ISSUE THREAD

**Issue by necouchman** [seancfoley/IPAddress#112]
I'm wondering if there's a clean way to create a list that contains both IPv4 and IPv6 addresses and loop over that list? I've got code that reads a comma-separated list of IP-type addresses and/or subnets and generates a list. Basically, it's using `IPAddressString` to parse the string and validate it, and then use the `getAddress()` method to retrieve the `IPAddress` value. The goal of this is to be able to take a list of both IPv4 and IPv6 addresses and put them into a single list, which I will then iterate through to check client addresses against.

My code is roughly this:
```
// Client address is retrieved from the request object
IPAddressString clientAddr = new IPAddressString(request.getRemoteAddr());

// This retrieves the list from the config file.
List<IPAddress> addrList = config.getAddresses();

for (IPAddress ipaddr : addrList) {
    if (ipaddr.contains(clientAddr.getAddress())) {
        // Do something here if the address matches
    }
}
```

However, when I try to do this, I'm getting the following error:
```
java.lang.ClassCastException: class inet.ipaddr.ipv4.IPv4Address cannot be cast to class inet.ipaddr.IPAddress (inet.ipaddr.ipv4.IPv4Address is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @4de78406; inet.ipaddr.IPAddress is in unnamed module of loader my.class.loader @48b3d6b6)
```
So, looks like `getAddress()` is returning the actual version-specific `IPAddress` (`IPv4Address` or `IPv6Address`), and the automatic conversion cannot take place (let alone the `contains()` call)?

Is there some elegant way to handle this that doesn't involve having to parse IPv4 and IPv6 into separate lists? I'm perfectly willing to make some `instanceof()` calls and check the class that way, but I'm not sure the best way to do that as a part of a loop?

**Comment by necouchman** [comment]
I tried to do something slightly different, and, instead, just go to `IPAddressString` objects instead of `IPAddress`, and I'm getting similar issues when trying to loop with a for loop:

```
class inet.ipaddr.IPAddressString cannot be cast to class inet.ipaddr.IPAddressString (inet.ipaddr.IPAddressString is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader 
```

Scratching my head on this one...

**Comment by seancfoley** [comment]
The exception is happening because you are loading two different versions of IPv4Address in two different classloaders. They are considered different classes. When you do that, it is true that an IPv4Address cannot be used as an IPv4Address.  The exception is telling you this.

**Comment by seancfoley** [comment]
One solution is to grab one of the two classloaders and use it to load the classes it is not loading.

**Comment by necouchman** [comment]
Thanks, @seancfoley, I appreciate your response on this. I'll look back through Maven dependencies and try to identify where the additional version is getting pulled in.

**Comment by necouchman** [comment]
Yeah, ended up being some duplicated dependencies in Maven. Interestingly it appears it was loading the same version, just loading it twice. Anyway, switching some of my pom.xml dependencies to `<scope>provided</scope>` seems to have resolved the issue.
