### ISSUE TITLE
How to quickly find all objects that may be associated with a specific IP address using IPAddressTrie by longest match?

### ISSUE THREAD

**Issue by wangchong2023** [seancfoley/IPAddress#115]
Thank you so much for your restoration, it helps our business tremendously!

Currently we have encountered another problem and would like to ask how to deal with it?
Also similar to the previous use case (object5 and object6 were added to the [last use case](https://github.com/seancfoley/IPAddress/issues/107)):
object1 associated address {1.1.1.0/24, 2.2.2.2/32}
object2 associated address (1.1.1.1/32, 3.3.3.3/32)
object3 associated address (2.2.2.0/24, 4.4.4.4/32)
object4 associated address (1.1.1.0/24, 5.0.0.0/16)
object5 associated address (1.1.1.1/32, 6.6.6.6/32)
object6 associated address (2.2.2.0/24, 7.7.7.7/32)

We need to find the longest matching object(s) with an IP address. For Example:
(1) To search 1.1.1.1, {object2, object5} need to be returned;
(2) To search 2.2.2.2, need to be matched with longest, {object1} need to be returned.

Can you help provide a code snippet, just like the previous issue, thank you very much for your help!

**Comment by seancfoley** [comment]
Why would 2.2.2.2 return {object3}. if object1 has associated address 2.2.2.2/32 and object6 has 2.2.2.0/24 just like object3?

**Comment by wangchong2023** [comment]
> Why would 2.2.2.2 return {object3}. if object1 has associated address 2.2.2.2/32 and object6 has 2.2.2.0/24 just like object3?
> 
> Wouldn't 2.2.2.2 return {object1}?

Because only the CIDR of object1 (2.2.2.2/32) is the longest match for 2.2.2.2, the other two objects (object3 and object6) are not the longest (only match 24 bits).
If there are multiple objects that satisfy the longest match, multiple objects that satisfy the longest match at the same time will be returned (for example, if 1.1.1.1/32 is matched, object2 and object5 will be returned).

**Comment by seancfoley** [comment]
object 1 has 2.2.2.2/32, not object 3

**Comment by seancfoley** [comment]
you said "if 2.2.2.2 is found, {object3} is returned"

**Comment by wangchong2023** [comment]
> object 1 has 2.2.2.2/32, not object 3

@seancfoley 
Sorry, I got some use cases wrong.Now I have fixed it.
Please help to check again and check if you still have any questions?
Thanks very much.

**Comment by seancfoley** [comment]
This is not much different than https://github.com/seancfoley/IPAddress/issues/107.

I added associatedObjects2 and associatedObjects3 to that code.
```
public class Code {

	public static void main(String[] args) {
		IPv4AddressAssociativeTrie<Objs> trie = construct();

		System.out.println("1.1.1.1 is associated with " + 
				associatedObjects2(trie, getAddr("1.1.1.1")));
		System.out.println("2.2.2.2 is associated with " + 
				associatedObjects2(trie, getAddr("2.2.2.2")));
		
		System.out.println("1.1.1.1 is associated with " + 
				associatedObjects3(trie, getAddr("1.1.1.1")));
		System.out.println("2.2.2.2 is associated with " + 
				associatedObjects3(trie, getAddr("2.2.2.2")));
	}
	
	static class Objs {
		Set<Object> objs = new HashSet<>();
		
		public String toString() {
			return objs.toString();
		}
	}
	
	static IPv4AddressAssociativeTrie<Objs> construct()  {
		IPv4AddressAssociativeTrie<Objs> trie = new IPv4AddressAssociativeTrie<>();
		Object object1 = new Object() {
			public String toString() {
				return "object1";
			}
		};
		Object object2 = new Object() {
			public String toString() {
				return "object2";
			}
		};
		Object object3 = new Object() {
			public String toString() {
				return "object3";
			}
		};
		Object object4 = new Object() {
			public String toString() {
				return "object4";
			}
		};
		Object object5 = new Object() {
			public String toString() {
				return "object5";
			}
		};
		Object object6 = new Object() {
			public String toString() {
				return "object6";
			}
		};
		associate(trie, getAddr("1.1.1.0/24"), object1);
		associate(trie, getAddr("2.2.2.2/32"), object1);
		associate(trie, getAddr("1.1.1.1/32"), object2);
		associate(trie, getAddr("3.3.3.3/32"), object2);
		associate(trie, getAddr("2.2.2.0/24"), object3);
		associate(trie, getAddr("4.4.4.4/32"), object3);
		associate(trie, getAddr("1.1.1.0/24"), object4);
		associate(trie, getAddr("5.0.0.0/16"), object4);
		associate(trie, getAddr("1.1.1.1/32"), object5);
		associate(trie, getAddr("6.6.6.6/32"), object5);
		associate(trie, getAddr("2.2.2.0/24"), object6);
		associate(trie, getAddr("7.7.7.7/32"), object6);
		
		System.out.println(trie);
		
		return trie;
	}
	
	static IPv4Address getAddr(String addrStr) {
		return new IPAddressString(addrStr).getAddress().toIPv4();
	}
	
	static <K extends IPAddress> void associate(AssociativeAddressTrie<K, Objs> trie, 
			K addr, Object obj)   {
		trie.remap(addr, objs -> {
			if(objs == null) {
				objs = new Objs();
			}
			objs.objs.add(obj);
			return objs;
		});
	}
	
	static <K extends IPAddress> Set<Object> associatedObjects( 
			AssociativeAddressTrie<K, Objs> trie, K addr)  {
		AssociativeTrieNode<K, Objs> containing = trie.elementsContaining(addr);
		Set<Object> result = new HashSet<>();
		if(containing != null) {
			do {
				result.addAll(containing.getValue().objs);
				AssociativeTrieNode<K, Objs> next = containing.getLowerSubNode();
				if(next == null) {
					next = containing.getUpperSubNode();
				}
				containing = next;
			} while(containing != null);
		}
		return result;
	}
	
	private static Set<Object> empty = new HashSet<>();
	
	static <K extends IPAddress> Set<Object> associatedObjects2( 
			AssociativeAddressTrie<K, Objs> trie, K addr)  {
		AssociativeTrieNode<K, Objs> containing = trie.elementsContaining(addr);
		if(containing != null) {
			while(true) {
				AssociativeTrieNode<K, Objs> next = containing.getLowerSubNode();
				if(next == null) {
					next = containing.getUpperSubNode();
					if(next == null) {
						return containing.getValue().objs;
					}
				}
				containing = next;
			}
		}
		return empty;
	}
	
	static <K extends IPAddress> Set<Object> associatedObjects3( 
			AssociativeAddressTrie<K, Objs> trie, K addr)  {
		AssociativeTrieNode<K, Objs> match = trie.longestPrefixMatchNode(addr);
		if(match != null) {
			return match.getValue().objs;
		}
		return empty;
	}
}
```
Output:
```

○ 0.0.0.0/0 (9)
└─○ 0.0.0.0/5 (9)
  ├─○ 0.0.0.0/6 (5)
  │ ├─● 1.1.1.0/24 = [object4, object1] (2)
  │ │ └─● 1.1.1.1 = [object5, object2] (1)
  │ └─○ 2.0.0.0/7 (3)
  │   ├─● 2.2.2.0/24 = [object3, object6] (2)
  │   │ └─● 2.2.2.2 = [object1] (1)
  │   └─● 3.3.3.3 = [object2] (1)
  └─○ 4.0.0.0/6 (4)
    ├─○ 4.0.0.0/7 (2)
    │ ├─● 4.4.4.4 = [object3] (1)
    │ └─● 5.0.0.0/16 = [object4] (1)
    └─○ 6.0.0.0/7 (2)
      ├─● 6.6.6.6 = [object5] (1)
      └─● 7.7.7.7 = [object6] (1)

1.1.1.1 is associated with [object5, object2]
2.2.2.2 is associated with [object1]
1.1.1.1 is associated with [object5, object2]
2.2.2.2 is associated with [object1]
```

**Comment by wangchong2023** [comment]
> This is not much different than #107.
> 
> I added associatedObjects2 and associatedObjects3 to that code.
> 
> ```
> public class Code {
> 
> 	public static void main(String[] args) {
> 		IPv4AddressAssociativeTrie<Objs> trie = construct();
> 
> 		System.out.println("1.1.1.1 is associated with " + 
> 				associatedObjects2(trie, getAddr("1.1.1.1")));
> 		System.out.println("2.2.2.2 is associated with " + 
> 				associatedObjects2(trie, getAddr("2.2.2.2")));
> 		
> 		System.out.println("1.1.1.1 is associated with " + 
> 				associatedObjects3(trie, getAddr("1.1.1.1")));
> 		System.out.println("2.2.2.2 is associated with " + 
> 				associatedObjects3(trie, getAddr("2.2.2.2")));
> 	}
> 	
> 	static class Objs {
> 		Set<Object> objs = new HashSet<>();
> 		
> 		public String toString() {
> 			return objs.toString();
> 		}
> 	}
> 	
> 	static IPv4AddressAssociativeTrie<Objs> construct()  {
> 		IPv4AddressAssociativeTrie<Objs> trie = new IPv4AddressAssociativeTrie<>();
> 		Object object1 = new Object() {
> 			public String toString() {
> 				return "object1";
> 			}
> 		};
> 		Object object2 = new Object() {
> 			public String toString() {
> 				return "object2";
> 			}
> 		};
> 		Object object3 = new Object() {
> 			public String toString() {
> 				return "object3";
> 			}
> 		};
> 		Object object4 = new Object() {
> 			public String toString() {
> 				return "object4";
> 			}
> 		};
> 		Object object5 = new Object() {
> 			public String toString() {
> 				return "object5";
> 			}
> 		};
> 		Object object6 = new Object() {
> 			public String toString() {
> 				return "object6";
> 			}
> 		};
> 		associate(trie, getAddr("1.1.1.0/24"), object1);
> 		associate(trie, getAddr("2.2.2.2/32"), object1);
> 		associate(trie, getAddr("1.1.1.1/32"), object2);
> 		associate(trie, getAddr("3.3.3.3/32"), object2);
> 		associate(trie, getAddr("2.2.2.0/24"), object3);
> 		associate(trie, getAddr("4.4.4.4/32"), object3);
> 		associate(trie, getAddr("1.1.1.0/24"), object4);
> 		associate(trie, getAddr("5.0.0.0/16"), object4);
> 		associate(trie, getAddr("1.1.1.1/32"), object5);
> 		associate(trie, getAddr("6.6.6.6/32"), object5);
> 		associate(trie, getAddr("2.2.2.0/24"), object6);
> 		associate(trie, getAddr("7.7.7.7/32"), object6);
> 		
> 		System.out.println(trie);
> 		
> 		return trie;
> 	}
> 	
> 	static IPv4Address getAddr(String addrStr) {
> 		return new IPAddressString(addrStr).getAddress().toIPv4();
> 	}
> 	
> 	static <K extends IPAddress> void associate(AssociativeAddressTrie<K, Objs> trie, 
> 			K addr, Object obj)   {
> 		trie.remap(addr, objs -> {
> 			if(objs == null) {
> 				objs = new Objs();
> 			}
> 			objs.objs.add(obj);
> 			return objs;
> 		});
> 	}
> 	
> 	static <K extends IPAddress> Set<Object> associatedObjects( 
> 			AssociativeAddressTrie<K, Objs> trie, K addr)  {
> 		AssociativeTrieNode<K, Objs> containing = trie.elementsContaining(addr);
> 		Set<Object> result = new HashSet<>();
> 		if(containing != null) {
> 			do {
> 				result.addAll(containing.getValue().objs);
> 				AssociativeTrieNode<K, Objs> next = containing.getLowerSubNode();
> 				if(next == null) {
> 					next = containing.getUpperSubNode();
> 				}
> 				containing = next;
> 			} while(containing != null);
> 		}
> 		return result;
> 	}
> 	
> 	private static Set<Object> empty = new HashSet<>();
> 	
> 	static <K extends IPAddress> Set<Object> associatedObjects2( 
> 			AssociativeAddressTrie<K, Objs> trie, K addr)  {
> 		AssociativeTrieNode<K, Objs> containing = trie.elementsContaining(addr);
> 		if(containing != null) {
> 			while(true) {
> 				AssociativeTrieNode<K, Objs> next = containing.getLowerSubNode();
> 				if(next == null) {
> 					next = containing.getUpperSubNode();
> 					if(next == null) {
> 						return containing.getValue().objs;
> 					}
> 				}
> 				containing = next;
> 			}
> 		}
> 		return empty;
> 	}
> 	
> 	static <K extends IPAddress> Set<Object> associatedObjects3( 
> 			AssociativeAddressTrie<K, Objs> trie, K addr)  {
> 		AssociativeTrieNode<K, Objs> match = trie.longestPrefixMatchNode(addr);
> 		if(match != null) {
> 			return match.getValue().objs;
> 		}
> 		return empty;
> 	}
> }
> ```
> 
> Output:
> 
> ```
> 
> ○ 0.0.0.0/0 (9)
> └─○ 0.0.0.0/5 (9)
>   ├─○ 0.0.0.0/6 (5)
>   │ ├─● 1.1.1.0/24 = [object4, object1] (2)
>   │ │ └─● 1.1.1.1 = [object5, object2] (1)
>   │ └─○ 2.0.0.0/7 (3)
>   │   ├─● 2.2.2.0/24 = [object3, object6] (2)
>   │   │ └─● 2.2.2.2 = [object1] (1)
>   │   └─● 3.3.3.3 = [object2] (1)
>   └─○ 4.0.0.0/6 (4)
>     ├─○ 4.0.0.0/7 (2)
>     │ ├─● 4.4.4.4 = [object3] (1)
>     │ └─● 5.0.0.0/16 = [object4] (1)
>     └─○ 6.0.0.0/7 (2)
>       ├─● 6.6.6.6 = [object5] (1)
>       └─● 7.7.7.7 = [object6] (1)
> 
> 1.1.1.1 is associated with [object5, object2]
> 2.2.2.2 is associated with [object1]
> 1.1.1.1 is associated with [object5, object2]
> 2.2.2.2 is associated with [object1]
> ```

Thank you very much for your help, any help is greatly appreciated.

When I re-examined this question, I found that this search logic does not seem to be the best performance for me now. Because after finding multiple associated objects based on the IP address, the object needs to be deduplicated (this is different from the previous business requirement of finding multiple objects. The current business only allows 1 to be found based on the longest match. objects).
In the current new business requirements, the data associated with the CIDR format IP address prefix to the object may be very large (millions), and the operation of finding the object with the longest matching IP prefix based on a single IP address is very frequent. .
Therefore, it may be more economical to deduplicate objects associated with the same prefix every time this massive data is loaded periodically (operation time is not sensitive). That is, when there are multiple identical IP prefixes associated with the same or different objects, the objects associated with the IP address prefixes are first deduplicated according to a certain factor, and then in the process of searching for associated objects with high-frequency IPs, the longest one is directly used. The matching algorithm found the expected object.
I

**Comment by seancfoley** [comment]
Just change your trie to use as its value:
```
static class ObjectAndWeight {
    Object obj;
    int weight;
}
```
Replace `class Objs` with that.

Then when you use any one of the searches I've provided (associatedObjects, associatedObjects2, associatedObjects3) choose the object from the returned set with the highest weight.
