### ISSUE TITLE
AddressDivisionBase dependent on  jdk 9

### ISSUE THREAD

**Issue by yuedaxia76** [seancfoley/IPAddress#121]
protected static final BigInteger BIG_MIN_RADIX = BigInteger.TWO,
			BIG_MAX_RADIX = BigInteger.valueOf(MAX_RADIX);

BigInteger.TWO is add in jdk 9

**Comment by yuedaxia76** [comment]
in README version 5.4.1 Requires Java 8 or higher. but not run on java 8.

**Comment by seancfoley** [comment]
Fixed in [version 5.4.2](https://github.com/seancfoley/IPAddress/releases/tag/v5.4.2).
