### ISSUE TITLE
Too short IP range when bits are set in first host address

### ISSUE THREAD

**Issue by jms4t** [seancfoley/IPAddress#122]
I'm facing an issue creating IP Ranges, 

What I expect:
```
IPAddressString("46.114.184.1/21").toSequentialRange() --> range: 46.114.184.1 to 46.114.191.255
...
IPAddressString("46.114.185.0/21").toSequentialRange() --> range 46.114.185.0 to 46.114.191.255
... 
``` 

What I get:
```
IPAddressString("46.114.184.1/21").toSequentialRange() --> range: 46.114.184.1 to 46.114.184.1
...
IPAddressString("46.114.185.0/21").toSequentialRange() --> range 46.114.185.0 to 46.114.185.0
... 
```

[here](https://jodies.de/ipcalc?host=46.114.184.1&mask1=21&mask2=) i find similar results to what i expected.
Is it a bug, or am i using it wrong? Please let me know :)

(I'm using the latest version 5.4.2)

**Comment by seancfoley** [comment]
With both your examples 46.114.184.1/21 and 46.114.185.0/21, the address is a CIDR address with a non-zero host, so it's parsed as a single address by this library, as well as by that page.

On the web-page you linked, the page makes the distinction between the address you've supplied and the associated subnet 46.114.184.0/21, and you need to do the same here.  You have a misunderstanding of what that page is telling you.  You are supplying an address, and it is telling you what subnet that address belongs to.  Both addresses you specified are in the same subnet, 46.114.184.0/21.  The page is also telling you the min and max host for that subnet if you want to exclude the network address 46.114.184.0 and the broadcast address 46.114.191.255, but those two addresses are still in the subnet.

Also note that there is no CIDR subnet from 46.114.185.0 to 46.114.191.255.  You should read up on CIDR to understand this.  For both addresses, the subnet is 46.114.184.0 to 46.114.191.255 or the subnet with network address 46.114.184.0/21.

So, in this library, you can get the subnet range 46.114.184.0 to 46.114.191.255 using the subnet address
```java
print(new IPAddressString("46.114.184.0/21").getAddress().toCanonicalWildcardString()); // the network address gives you the network
print(new IPAddressString("46.114.184.0/21").getAddress().toSequentialRange());
print(new IPAddressString("46.114.184.0/21").getSequentialRange());

static void print(Object o) {
	System.out.println(o);
}
```
```
46.114.184-191.*
46.114.184.0 -> 46.114.191.255
46.114.184.0 -> 46.114.191.255
```

For any address, including those with non-zero host, you can get the subnet using toPrefixBlock:
```java
print(new IPAddressString("46.114.184.1/21").getAddress().toPrefixBlock().toSequentialRange()); // convert to network address
print(new IPAddressString("46.114.185.0/21").getAddress().toPrefixBlock().toSequentialRange()); 
```
```
46.114.184.0 -> 46.114.191.255
46.114.184.0 -> 46.114.191.255
```

The above is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address) and this [entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment,-Matching,-Comparing#containment-within-the-enclosing-cidr-prefix-block).

You can also use range notation:
```java
print(new IPAddressString("46.114.184-191.*").getSequentialRange()); // just be explicit
print(new IPAddressString("46.114.184-191.0-255").getSequentialRange());
```
```
46.114.184.0 -> 46.114.191.255
46.114.184.0 -> 46.114.191.255
```

You can also construct addresses individually to specify any given range, including those not corresponding to a CIDR subnet:
```java
print(new IPv4AddressSeqRange(new IPAddressString("46.114.184.1").getAddress().toIPv4(), new IPAddressString("46.114.191.255").getAddress().toIPv4())); // create range directly from boundaries
print(new IPv4AddressSeqRange(new IPAddressString("46.114.185.0").getAddress().toIPv4(), new IPAddressString("46.114.191.255").getAddress().toIPv4()));
```
```
46.114.184.1 -> 46.114.191.255
46.114.185.0 -> 46.114.191.255
```

**Comment by jms4t** [comment]
Thanks for elaborating, much appreciated.

Actually I have the requirement to parse ``46.114.184.1/21`` to ``46.114.184.1 -> 46.114.191.255``.

I think this can be done like this:
```
new IPv4AddressSeqRange(
                new IPAddressString("46.114.184.1/21").getAddress().toIPv4(),
                new IPAddressString("46.114.184.1/21").getAddress().toPrefixBlock().getUpper().toIPv4()
        );
```

Can it be done independent of the IP Version? - IPv4 / IPv6
(without _if-ipv4_, _if-ipv6_ conditions)

**Comment by jms4t** [comment]
Thanks a lot.
