### ISSUE TITLE
Is there a method for parse string from IPAddress::toFullString back to IPAddress

### ISSUE THREAD

**Issue by lavrukov** [seancfoley/IPAddress#123]
IPAddress have method witch returns for address "0.0.50.0" String "000.000.050.000".

Could you help me please: how to parse this string back? I try IpAddressString but it's parse "000.000.050.000" to address "0.0.40.0". It looks like IpAddressString  think that 050 is oct.

I can parse it with InetAddress.getByName but it's too dangerous - this method can use DNS.

**Comment by seancfoley** [comment]
The reason it parses differently is that if is interpreted as octal.  Each segment that starts with 0 is octal, each segment that starts with 0x is hexadecimal.

If you type http://000.000.050.000 into the address bar of some browsers, you will see it is interpreted as 0.0.40.0.

Those strings are IPv4 string formats originally introduced by the [inet_aton](https://linux.die.net/man/3/inet_aton) utility in BSD Unix. Those formats have persisted with inet_aton in the various Unix and Linux flavours, while spreading elsewhere into browsers and other software.

If you wish, you can treat such addresses as invalid, using [validation parameters](https://seancfoley.github.io/IPAddress/ipaddress.html#address-or-host-name-validation-options), giving you the result you want. 

```java
IPAddressString ipAddrStr = new IPAddressString("0.0.50.0");
IPAddress ipAddr = ipAddrStr.getAddress();
IPAddressStringParameters strParams = 
	new IPAddressStringParameters.Builder().allow_inet_aton(false).toParams();
ipAddrStr = new IPAddressString(ipAddr.toFullString(), strParams);
ipAddr = ipAddrStr.getAddress();
System.out.println(ipAddr);
```
Output:
```
0.0.50.0
```
or make it default behaviour using fixed params with your own class
```java
class MyStringClass extends IPAddressString {
	MyStringClass(String name) {
		super(name, strParams);
	}
}
```

**Comment by lavrukov** [comment]
I understood that this IP address may not be translated correctly in some systems, but I have particular task and want to use this way only for serialization/deserialization for DB.

Thank you so much, allow_inet_aton(false) is works! It was very difficult to find an answer, because i didn't see it in docs of IPAddressStringParameters and just was blind when read docs for IPAddressString https://javadoc.io/doc/com.github.seancfoley/ipaddress/5.3.3/inet/ipaddr/IPAddressString.html. Only now i found sentence with answer for my question. 

But, there is only way to parse with specific IPv4AddressStringParameters. I understand, that this problem could be only with IPv4 addresses and because of it there isn't needed this method in IPAddressStringParameters interface, but I use a generic code for serialization ipv4/ipv6 code and generic code for deserialization, and because of it want to have symmetrical possibility to parse from toFullString()

Thank you!
