### ISSUE TITLE
InetAddressValidator.isValidInet4Address() and InetAddressValidator.isValidInet6Address() behave differently for subnets with /cidr

### ISSUE THREAD

**Issue by jspyeatt** [seancfoley/IPAddress#128]
`InetAddressValidator.isValidInet4Address("172.10.10.0/24")` returns `false`
while
`InetAddressValidator.isValidInet6Address("2001:0DB8:2CA1:0001:0000:0567:5673:2300/124")` returns `true`.

This seems like inconsistent behavior when a CIDR notation string is specified.

Looking at the code ipv4Validator performs a typical ipv4 regex match so the /CIDR notation returns false. 

While the validation for ipv6 splits out the '/' into parts and continues to perform validation including CIDR length checks.

I'm not certain if the intention of these two methods is to consider /CIDR strings valid or not, otherwise I would submit a fix. But I believe they should be consistent.

**Comment by seancfoley** [comment]
`InetAddressValidator` is not in this library.  It is in [Apache Commons](https://commons.apache.org/).

**Comment by seancfoley** [comment]
In this library you'd parse either one with `new IPAddressString(string).isValid()` and it would return true in both cases.
