### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by tapir** [seancfoley/IPAddress#16]
Although I can work with ipaddress outside of an android project, when I'm trying in one I get this error

```ipaddress-5.0.1.jar: D8: Illegal class file: Class module-info is missing a super type.```

Any ideas?

**Comment by seancfoley** [comment]
The module-info is used only with Java 9 and up for the new "Jigsaw" module feature added with Java 9:
https://www.oracle.com/corporate/features/understanding-java-9-modules.html

I added that file only for those who wished to use Java 9 modules.  Using modules is somewhat optional (you can choose to put everything in the default module).

AFAIK Android does not yet support Java 9, but does support most, if not all, of Java 8.  Certainly, it sounds like your android version does not support Java 9 modules.
https://stackoverflow.com/questions/47627499/does-android-studio-3-support-java-9-for-android-development-if-so-what-featur

So you can just delete that file module-info.java, it doesn't need to be there when not using modules.

**Comment by seancfoley** [comment]
Perhaps I will add another jar file that does not have module-info inside.  In reality the file should be ignored when not using modules but I guess your android environment is not ignoring it.  You can just use any zip-file tool (winzip, gzip, winrar, zip, etc) to remove the module-info class file from your jar file (a jar file is actually a zip file).

**Comment by tapir** [comment]
I see. Thanks for the info.

I'm using gradle for dependencies and it pulls everything from mavenCentral
so I think there is no permenant way for me to remove that file without
having a local repo.

So if it's not too much of hassle I would be grateful if you could have
another jar like you mentioned.

BTW I'm using react native and its build environment. It's likely that
people using react native will get the exact same error.

Thanks

**Comment by seancfoley** [comment]
OK, seems you are not the first to encounter this.
https://github.com/Azure/azure-iot-sdk-java/issues/302
https://github.com/Fazecast/jSerialComm/issues/128
https://github.com/Azure/azure-iot-sdk-java/issues/313
https://github.com/JodaOrg/joda-money/issues/94
https://github.com/Leanplum/Leanplum-Android-SDK/issues/251

Not sure if anyone found a nice solution in any of those other issues.

I'll have to give this a little thought.

**Comment by seancfoley** [comment]
Strangely, there appear to be no simple solution from any of Maven, Android Studio, Java, or Gradle, although eventually Android Studio will likely have some kind of fix.  

From what I can tell, what others have done:

1. put separate jar on maven just for android, which seems like a lot of extra overhead just to delete a single small file

2. there appears to be a jarjar tool some have used, such as in that fazecast bug above https://github.com/Fazecast/jSerialComm/issues/128#issuecomment-409315301
and here https://stackoverflow.com/questions/44913406/exclude-one-class-file-in-gradle-android-studio
This appears to be the tool: https://github.com/shevek/jarjar
Looks like you would need something like this:

		dependencies {
			// Use jarjar.repackage in place of a dependency notation.
			compile jarjar.repackage {
				from 'com.github.seancfoley:ipaddress:5.0.1'

				classDelete "module-info.class"
			}
		}
    
There is a complete example build file here: https://github.com/shevek/jarjar/blob/master/jarjar-gradle/example/build.gradle
Can you try this second option?

**Comment by tapir** [comment]
looks like a good solution to me. thanks

**Comment by seancfoley** [comment]
@tapir Have you tried it?  If and when you try it, can you let me know if it works?

**Comment by tapir** [comment]
Sorry it took a while. Most of the time I've spent went to solve how to apply gradle plugins. TL,DR: It works.
I consider this issue solved.

**Comment by seancfoley** [comment]
@tapir Great!  Good to know it works.  Also, keep in mind Android Studio will almost certainly have its  own fix eventually.

**Comment by seancfoley** [comment]
This appears to have been fixed in [Android Studio 3.3](https://androidstudio.googleblog.com/2018/06/android-studio-33-canary-1-available.html) 

> Processing module-info.class during desugaring analysis caused failures with the message java.lang.IllegalArgumentException: Type without superclass: module-info. This file is now filtered out during desugaring analysis.
