### ISSUE TITLE
Merge Subnet Ranges

### ISSUE THREAD

**Issue by onderson** [seancfoley/IPAddress#18]
What i want to achieve with this library is something mentioned here?

https://github.com/flowchartsman/cidr-convert

Is is possible? I have seen examples on SO. but nothing similar to this c equivalent.
Could you please take a look and potentially provide some examples to give an idea on how to implement?

Cheers

**Comment by onderson** [comment]
I came up with something like this;

IPAddressString ipAddressString = new IPAddressString("10.0.80.80/31");
IPAddressString ipAddressString2 = new IPAddressString("10.0.80.82/31");
IPAddressString ipAddressString3 = new IPAddressString("10.0.80.88/30");

IPAddress first = ipAddressString.getAddress();
IPAddress second = ipAddressString2.getAddress();
IPAddress third = ipAddressString3.getAddress();

IPAddress[] blocks = first.mergeToPrefixBlocks(second,third);
		
System.out.println("blocks are " + Arrays.asList(blocks));

**Comment by seancfoley** [comment]
Yes, that should do it.

    blocks are [10.0.80.80/30, 10.0.80.88/30]

Also some sample code here: https://stackoverflow.com/questions/12514752/convert-ip-array-to-smallest-cidr-subnet-list-in-java/55331360#55331360

It's similar to what you have above.

Also there is a method mergeToSequentialBlocks which is similar but doesn't merge to CIDR notation, instead merges to subnets with segments shown as ranges, which can be a shorter list in some cases.

    blocks are [10.0.80.80-83, 10.0.80.88-91]

**Comment by seancfoley** [comment]
Also, there is the method spanWithPrefixBlocks with will list all CIDR blocks between any two addresses.

So that covers all the functionality offered in the C and go language tool that you've linked to.

Also note this code here works the same with IPv6.
