### ISSUE TITLE
IPv6 CIDR block is created for Hex IPv4 IP ranges

### ISSUE THREAD

**Issue by oomphfortuity** [seancfoley/IPAddress#23]
I have two Hex IPv4 ranges from which i want to create cidr blocks.
StartIP - 0000000000000000000000000A000000  (10.0.0.0)
EndIP  -  0000000000000000000000000AFFFFFF   (10.255.255.255)

```
IPAddress start = 
new IPAddressString("0000000000000000000000000A000000").getAddress();

IPAddress end = 
new IPAddressString("0000000000000000000000000AFFFFFF").getAddress();

IPAddress cidrs[] = start.toSequentialRange(end).spanWithPrefixBlocks();

//output of cidrs[] = [::a00:0/104]

```
It is giving ::a00:0/104 block for IPV4 range . Instead it should give 10.0.0.0/8 block.

**Comment by seancfoley** [comment]
This is not much different than your issue 22.  

If it is a hex IPv4 address, that fits into 8 characters, and since IPv4 is by default decimal, add a 0x to indicate hex.  

		IPAddress start =  new IPAddressString("0x0A000000").getAddress();
		IPAddress end =  new IPAddressString("0x0AFFFFFF").getAddress();
		IPAddress cidrs[] = start.toSequentialRange(end).spanWithPrefixBlocks();
		System.out.println(Arrays.asList(cidrs));

output:

    [10.0.0.0/8]

To convert:

		String str = "0000000000000000000000000A000000";
		String ipv4Hex ="0x" + str.substring(str.length() - 8);
		System.out.println(ipv4Hex);

output:

    0x0A000000

**Comment by oomphfortuity** [comment]
Below code would be better

```
private static String toShortHex(String ip){
       if ((ip = ip.toUpperCase()).startsWith("0X")) {
           ip = ip.replace("0X", "");
       }
       String shortHex = new BigInteger(ip, 16).toString(16);
       return (shortHex.length () % 2 == 0 ? "0x" : "0x0") + shortHex;
 }
```

**Comment by seancfoley** [comment]
If you are going to use BigInteger to parse, there is no need to parse a second time. Just construct IPv4Address directly with the right [constuctor](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4Address.html#IPv4Address-byte:A-):

		IPAddress address = new IPv4Address(new BigInteger("0000000000000000000000000A000000", 16).toByteArray());
		IPAddress address2 = new IPv4Address(new BigInteger("0000000000000000000000000AFFFFFF", 16).toByteArray());
		IPAddress blocks[] = address.toSequentialRange(address2).spanWithPrefixBlocks();
		System.out.println(Arrays.asList(blocks));

output:

    [10.0.0.0/8]

**Comment by seancfoley** [comment]
Also, if you can use [IPAddressGenerator.from](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddressNetwork.IPAddressGenerator.html#from-byte:A-) to generate either IPv4 or IPv6 addresses from bytes.  It will produce IPV6 if there are at least 16 bytes, IPv4 otherwise.

		IPAddressGenerator generator = new IPAddressGenerator();
		IPAddress address = generator.from(new BigInteger("0000000000000000000000000A000000", 16).toByteArray());
		IPAddress address2 = generator.from(new BigInteger("0000000000000000000000000AFFFFFF", 16).toByteArray());
		IPAddress blocks[] = address.toSequentialRange(address2).spanWithPrefixBlocks();
		System.out.println(Arrays.asList(blocks));

output:

    [10.0.0.0/8]

**Comment by seancfoley** [comment]
Lastly, for IPv4, you can just use Integer instead of BigInteger:

		IPAddress address = new IPv4Address(Integer.parseInt("0000000000000000000000000A000000", 16));
		IPAddress address2 = new IPv4Address(Integer.parseInt("0000000000000000000000000AFFFFFF", 16));
		IPAddress blocks[] = address.toSequentialRange(address2).spanWithPrefixBlocks();
		System.out.println(Arrays.asList(blocks));

**Comment by seancfoley** [comment]
This is essentially the same issue as https://github.com/seancfoley/IPAddress/issues/22 and the solutions are [summarized there](https://github.com/seancfoley/IPAddress/issues/22#issuecomment-499947866) and in the examples above.
