### ISSUE TITLE
eclipse project kept showing error

### ISSUE THREAD

**Issue by wei0313** [seancfoley/IPAddress#25]
Hi

I  kept getting the following error when import ipaddress-5.0.2.jar to my eclipse project. 
`The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files`

Could you please provide some info how I can resolve this issue? 

My eclipse version is  Version: Oxygen.3a Release (4.7.3a) Build id: 20180405-1200
attached my build path and build java version
<img width="782" alt="Screen Shot 2019-07-22 at 9 38 09 PM" src="https://user-images.githubusercontent.com/11778778/61683135-48b90600-acc9-11e9-80b1-29fb0fc5056c.png">
 
<img width="794" alt="Screen Shot 2019-07-22 at 9 35 47 PM" src="https://user-images.githubusercontent.com/11778778/61683044-e5c76f00-acc8-11e9-95d9-efe0589c71fd.png">

If I compile in the command line, it's compiled fine. It seems like only happens in eclipse. 

Thanks

**Comment by seancfoley** [comment]
This is not an issue with the IPAddress library.  Possibly an Eclipse issue.

https://stackoverflow.com/questions/18075343/java-project-in-eclipse-the-type-java-lang-object-cannot-be-resolved-it-is-ind
https://stackoverflow.com/questions/13225363/error-in-eclipse-for-android-the-type-java-lang-string-cannot-be-resolved-it/13225387

I suspect it may be your use of modules.  Modules were introduced with Java 9, but you are using a Java 8 JRE.  You don't need to use IPAddress as a module.  Try moving IPAddress.jar from the module path to the class path.  Try deleting module-info.class from the IPAddress jar file (you can use any zip file editor to do this, jar files are zip files).

**Comment by seancfoley** [comment]
Also make sure your compiler level is set to 1.8 when using a Java 8 JRE - preferences -> java -> compiler -> compiler compliance level

**Comment by wei0313** [comment]
Thanks :) I figured that out in the morning was about to upgrade the thread.
