### ISSUE TITLE
IP network mask

### ISSUE THREAD

**Issue by mkpaz** [seancfoley/IPAddress#27]
Suppose, we have an adress string and ones need to get IPv4 netmask address in octet format.

```java
IPAddress ipv4Address = new IPAddressString("1.2.3.4/24").toAddress();
System.out.println(ipv4Address.getNetwork().getNetworkMask(ipv4Address.getNetworkPrefixLength()));
```

This code does its work, but it literally requires to specify the network prefix twice. First in the address string and then as arg in `getNetworkMask()`. Would it be possible to add `getNetworkMask()` method to `IPAddress` or inherit prefix length from IPAddress in `getNetwork()` ?

**Comment by seancfoley** [comment]
Yes, that seems reasonable.

**Comment by seancfoley** [comment]
This has been added to versions 4.3.1 and 5.1.0, getNetworkMask and getHostMask.  Also added toZeroNetwork as mentioned in issue #28.
