### ISSUE TITLE
判断IP是否在该网段中的contains方法准确性不高

### ISSUE THREAD

**Issue by Eternally8** [seancfoley/IPAddress#31]
val ipObject = new IPAddressString("10.168.1.2")
val maskObject = new IPAddressString( "10.168.0.224/23")
return maskObject.contains(ipObject) 为false,理论上应该是为true

**Comment by seancfoley** [comment]
According to google translate, you are saying "The contains method of determining whether the IP is in the network segment is not accurate".

This is essentially identical to the previous issue #30 or issue #26 .

10.168.0.224/23 is not a subnet. 10.168.0.0/23 is a subnet.

In this library, parsing will give you a prefix block subnet if the host is zero (or in other words, it is the network address).  The host here is the 9 bits that start at the last bit of segment 3 and cover segment 4.

So you either need to use the network address:
```java
 boolean contains = new IPAddressString("10.168.0.0/23").
    contains(new IPAddressString("10.168.1.2")); //true
```

or you need to convert to a subnet address:
```java
boolean contains = new IPAddressString("10.168.0.224/23").getAddress().toPrefixBlock().
    contains(new IPAddressString("10.168.1.2").getAddress()); //true
```

See here for more details: https://github.com/seancfoley/IPAddress/wiki/Code-Examples#parse-prefixed-as-subnet-or-ip-address
Or the section "**Prefixed Addresses and toHostAddress()**" here: https://seancfoley.github.io/IPAddress/#_Toc525135535

**Comment by seancfoley** [comment]
I can see you are using Kotlin.

Here are the same examples in Kotlin.
Use the network address:
```kotlin
val contains = IPAddressString("10.168.0.0/23").
    contains(IPAddressString("10.168.1.2")) //true
```
Convert to prefix block:
```kotlin
val contains2 = IPAddressString("10.168.0.224/23").address.toPrefixBlock()?.
    contains(IPAddressString("10.168.1.2").address) //true
```
