### ISSUE TITLE
Get Network Class

### ISSUE THREAD

**Issue by somejavadev** [seancfoley/IPAddress#35]
Hi,

Absolutely loving this API. I just want to find out, is there a way to get the Network class of a given CIDR?  Something in the lines of:
```java
IPAddress addr = new IPAddressString( "10.0.0.0/8").getAddress();
System.out.println(addr.getNetworkClass()) // Prints A and in other scenarios B, C or D
```

**Comment by somejavadev** [comment]
I have found the solution to this in one of the closed tickets.

https://github.com/seancfoley/IPAddress/issues/21

**Comment by seancfoley** [comment]
Yes, this one is likely the one you saw: https://github.com/seancfoley/IPAddress/issues/21 

Maybe I will add this to the IPv4Address class since this is the second request. Previously I thought this just wasn't used much anymore.
