### ISSUE TITLE
Support for Binary IPv4

### ISSUE THREAD

**Issue by rdonuk** [seancfoley/IPAddress#38]
Hi, I am trying this code:
```
IPAddressString ipAddrStr = new IPAddressString("11000000.10101000.00000001.00000001");
if (ipAddrStr.isIPv4()) {
	try {
		IPAddress ipv4Addr = ipAddrStr.toAddress().toIPv4();
		if (ipv4Addr != null) {
			unescapedHost = ipv4Addr.toString();
		}
	} catch (AddressStringException e) {
		// Do something
	}
}
```

And `ipAddrStr.isIPv4()` returns false. Support for binary IPv4 could be added?

Thank you.

**Comment by seancfoley** [comment]
Can't say I've seen binary IPv4 before.  Is there a context in which this format is used?  For IPv4, there is generally decimal n.n.n.n, or octal 0n.0n.0n.0n, or hex 0xn.0xn.0xn.0xn and these can be mixed together like n.0n.0xn.n.  In fact, I believe the code would parse "00000000.00000000.00000001.00000001", it would be the same as 0.0.1.1 or octal 00.00.01.01 or hex 0x0.0x0.0x1.0x1.  But on the flip side perhaps it could give 8 digits of 0/1 special meaning.  But I can't say I've seen binary used anywhere.

**Comment by seancfoley** [comment]
This may or may not be added in a future release, but closing this bug since there has been no response to my queries.

**Comment by seancfoley** [comment]
Binary parsing was added to version 5.3.2

`IPAddressString ipAddrStr = new IPAddressString("0b11000000.0b10101000.0b1.0b1");`
