### ISSUE TITLE
Duplicate property key

### ISSUE THREAD

**Issue by andyadc** [seancfoley/IPAddress#41]
IPAddressResources.properties
ipaddress.error.splitMismatch=splitting digits in segments results in an invalid string (eg 12-22 becomes 1-2.2-2 which is 12 and 22 and nothing in between)
ipaddress.error.splitMismatch=split segments cannot be range segments

**Comment by seancfoley** [comment]
Thanks youAndy, for finding that.  Is this causing any problems with your language or platform?  Just curious if it's a small issue or a bigger one.

**Comment by seancfoley** [comment]
Fixed in version 5.3.2
