### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by otlg** [seancfoley/IPAddress#43]
Hi,

I've started to evaluate the IPAddress component and faced with few validation issues of IPAddressString.

For example: IPs like `127.0.1`, `2001:____:a::123/64`, `2001:0db8:85a3:-:0000:8a2e:0370:7334` are valid while they are not. 
Is it an API bug or wrong validation configuration? For example, DEFAULT_VALIDATION_OPTIONS should be changed. If yes, what are right validation options that should be applied?

I see that:
`127.0.1` transformed to `127.0.0.1`
`____` transformed to `*`
`-` transformed to `*`

How this transformation can be disabled?

Thanks,
Oleg.

**Comment by seancfoley** [comment]
Regarding your examples,

For 127.0.1 see issue #19. If you type that into firefox (ie http://127.0.1) you'll see it's a valid address.

For 2001:____:aa::123/64, the _ is a wildcard to represent any digit.  

For 2001:0db8:85a3:-:0000:8a2e:0370:7334. the address allows you to omit the boundary of a range, in which case there is no boundary, so - is equivalent to 0-ffff in the context of IPv6.

As explained in the [docs](https://seancfoley.github.io/IPAddress/), this library will "Allow control over which formats are allowed when parsing".  The docs also describe all of these address formats.

As explained in the [section "Address or Host Name Validation Options"](https://seancfoley.github.io/IPAddress/ipaddress.html#parse-string-representation-of-ip-address-or-host-name), "Validation options allow you to restrict the allowed formats" and "The default options used by the library are permissive and not restrictive" and there is an example there with `HostNameParameters` showing how the builder pattern is used to construct validation options.

The options are available in the javadoc for [AddressStringParameters](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/AddressStringParameters.html) and [IPAddressStringParameters](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddressStringParameters.html) and [IPv4AddressStringParameters](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4AddressStringParameters.html) and [IPv6AddressStringParameters](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv6/IPv6AddressStringParameters.html) and [HostNameParameters](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/HostNameParameters.html)

I'm guessing you want [allow_inet_aton](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddressStringParameters.Builder.html#allow_inet_aton-boolean-) and you want [allowsSingleWildcard](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/AddressStringParameters.RangeParameters.html#allowsSingleWildcard--) and you want [allowsInferredBoundary](allowsInferredBoundary-) and any number of other ["allow" methods](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/index-all.html).
