### ISSUE TITLE
Wrong super method called in AssociativeAddressTrie.elementsContaining

### ISSUE THREAD

**Issue by spencejackson** [seancfoley/IPAddress#44]
Currently calling super.elementsContainedBy
Should call super.elementsContaining

**Comment by seancfoley** [comment]
yes, right [here](https://github.com/seancfoley/IPAddress/blob/master/IPAddress/src/inet.ipaddr/inet/ipaddr/format/util/AssociativeAddressTrie.java#L607), you are correct

**Comment by seancfoley** [comment]
As a work-around you can call getRoot().elementsContaining

**Comment by seancfoley** [comment]
Fixed in version 5.3.2
