### ISSUE TITLE
IPAddressString.toAddress() doesn't fail as expected with an incomplete IPv4 address.

### ISSUE THREAD

**Issue by attrout** [seancfoley/IPAddress#47]
Current Behavior:
Incomplete IPv4 address strings don't fail to parse as expected when put in an IPAddressString and converted to an address with toAddress().  For example, the string "192.168" will be parsed as "192.0.0.168", and "192.168.1" will be parsed as "192.168.0.1", instead of throwing an exception.

Expected Behavior:
An exception is thrown.

Reproduction:
  @Test
  void reproduction() throws AddressStringException {
    String input = "192.168";
    IPAddressString ipAddressString = new IPAddressString(input);
    IPAddress ipAddress = ipAddressString.toAddress();
    assertEquals("192.0.0.168", ipAddress.toCanonicalString());
  }

Versions:
Library version: 5.3.1
Java version: AdoptOpenJDK 11.0.6

**Comment by attrout** [comment]
Turns out this was expected behavior, and the problem is with me.  Sorry.

**Comment by seancfoley** [comment]
No problem, this has caused confusion on more than one occasion, such as issue #19 and issue #42, so I have created a wiki entry to [cover this](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#control-parsing-of-ip-addresses-with-fewer-segments-than-standard).
