### ISSUE TITLE
Cannot use library as Maven dependency when jitpack.io repo is added

### ISSUE THREAD

**Issue by gagarski** [seancfoley/IPAddress#49]
For some reason jitpack.io repository has broken builds of some (not all versions of your library). These jars are almost empty and contain no classes at all. 

I understand that jitpack.io builds packages "on demand" when any user first requests them but I don't understand why there are builds of your library there and why does not it have all the versions. For example, it already has 5.3.3 version but does not have 5.3.0.

Also I don't know why does it even publishes anything (Brief look at [this page](https://jitpack.io/docs/BUILDING/) suggests that by default it tries to run build tools from the root of the repo and `mvn install -DskipTests` definitely fails if you run it from the root of the repo).

Also I don't know how to solve it. Maybe it's possible to make your repo jitpack-compatible by providing `jitpack.yml` (probably we do not consider changing the artifact name).

**Comment by gagarski** [comment]
While I was writing this I probably solved most of the mysteries.
 - Careful reading jitpack docs revealed the following:
   > If the project has a build.gradle file then it will be built using Gradle otherwise JitPack will look for a pom.xml, build.sbt or project.clj file. The build.gradle file can also be located in a subfolder.
    You definitely have `pom.xml` in a subfolder, that what makes it build.
 - Your `pom.xml` produces empty jar which is found on jitpack. (because you use ant to build)
 - Also I found out that for jitpack I should specify a tag name which is `v5.3.0` for version 5.3.0. Doing that caused to produce a wrong build in jitpack repo. (Hooray?)
 - One mystery left is why jitpack has `5.3.3`, `5.3.2` etc versions (without `v`). It could be explained you you have these tags earlier in your repo.

**Comment by gagarski** [comment]
#50 will prevent future versions from being published. You may also login to Jitpack and remove old versions from there (the last mystery still remains).

**Comment by seancfoley** [comment]
Thanks for the notification.  I've never heard of jitpack until this issue.  Seems lots of people have tried downloading from there, with 800 attempts the last month.  Obviously they find out quickly that those downloads don't work.
One of my first thoughts is why do they publish jars that are empty?  You can see in their build logs "[WARNING] JAR will be empty - no content was marked for inclusion!" and yet they go ahead and publish an empty jar anyway and make the claim it's a usable jar.  Not a good citizen of the internet.

**Comment by seancfoley** [comment]
They recommend: ["Note: when using multiple repositories in build.gradle it is recommended to add JitPack at the end."](https://jitpack.io/docs/#building-with-jitpack) Most likely the recommend for this very reason.  IPAddress is on both maven central and jcenter, so it should find it in either one of those places first.  You could try that.

**Comment by gagarski** [comment]
> You can see in their build logs "[WARNING] JAR will be empty - no content was marked for inclusion!" and yet they go ahead and publish an empty jar anyway and make the claim it's a usable jar. Not a good citizen of the internet.

The thing is that they probably don't do that explicitly. Jitpack publishes them automatically when someone adds the library to `pom.xml`/`build.gradle` with Jitpack repo enabled (Maven/Gradle asks Jitpack for a package and when if the package is missing instead of returning 404 it builds is and returns the built JAR). It's like add any Github repo as a dependency without worrying if someone published it to Maven Central or JCenter.

> They recommend: "Note: when using multiple repositories in build.gradle it is recommended to add JitPack at the end." Most likely they recommend that for this very reason.

When you use Maven and add repository, Maven Central usually is not added manually but inherited from default pom.xml. Seems like Maven inheritance works by adding repos from child POM before repos from parent POM . This can be worked around by adding Maven Central explicitly to you project though.

**Comment by seancfoley** [comment]
In my comment "they" refers to Jitpack owners/maintainers/developers, not users of Jitpack.  Jitpack should not publishing empty "fake" jars of other peoples' repos.

**Comment by gagarski** [comment]
Well, that's questionable. First, "JAR will be empty" is a warning, not an error. Warnings do not prevent build (if you run `mvn clean package` locally you will have the same empty JAR). Second, this way they should parse maven output which is probably not easy and pleasant thing to do even if you are a cloud build service developer (also they should parse Gradle, SBT or even almost arbitrary build tool run from `jitpack.yaml`). Third, having `pom.xml` that produces empty JAR is quite rare case.

> Jitpack should not publishing empty "fake" jars of other peoples' repos.

It's not fake, it's the one produced by your `pom.xml`.

Actually the one questionable thing done by them here is a takeover of a `com.github` artifact group (though probably `com.github.whoever` looks nicer than `io.jitpack.github.whoever`)

**Comment by seancfoley** [comment]
It looks like jitpack is no longer being maintained.  They have not responded to my queries.  They have over 2000 open issues.  There has not been a single commit since May.  They ignore the questions posed to them on their own chat channel on their own web site.  They ignore emails.  They provide no way at all to delete a release from their repo, regardless of whether their build actually worked or not, regardless of whether the project owner wants it there or not, they just put up empty fake jars and leave them there.  The only solution is for you to access IPAddress releases from maintained repos that actually work properly.  IPAddress is available from maven central or bintray jcentral.  Do not use jitpack to access IPAddress releases.

**Comment by Frederick888** [comment]
Just wanna leave a comment for anyone who's got this problem in the future:

https://stackoverflow.com/a/41810983/2487227 fixed this problem for me. Basically you want to tell Maven to prefer Maven Central over Jitpack:
```xml
<repositories>
    <repository>
        <id>1_maven.apache.org</id>
        <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <repository>
        <id>2_jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
