### ISSUE TITLE
Trying to merge two ip-addresses which seems to be giving incorrect result

### ISSUE THREAD

**Issue by prateekbansal** [seancfoley/IPAddress#56]
I am new to this library. I am trying to understand more about CIDRs and how to use this library.

I am trying to run this test:
` @Test
    public void test() {
        final IPAddress first = new IPAddressString("10.1.150-250.0/23").getAddress();
        final IPAddress second = new IPAddressString("10.1.130-149.0/23").getAddress();
        final IPAddress[] merged = first.mergeToPrefixBlocks(second);

        for (IPAddress ipAddress : merged) {
            System.out.println(ipAddress.toConvertedString());
        }
`

I was expecting an output like "10.1.130-250.0/23" or even a result same as output. However, I get this instead:
`
10.1.130.0/32
10.1.131.0/32
10.1.132.0/32
10.1.133.0/32
10.1.134.0/32
10.1.135.0/32
10.1.136.0/32
10.1.137.0/32
10.1.138.0/32
10.1.139.0/32
10.1.140.0/32
10.1.141.0/32
10.1.142.0/32
10.1.143.0/32
10.1.144.0/32
10.1.145.0/32
10.1.146.0/32
10.1.147.0/32
10.1.148.0/32
10.1.149.0/32
10.1.150.0/23
10.1.152.0/21
10.1.160.0/19
10.1.192.0/19
10.1.224.0/20
10.1.240.0/21
10.1.248.0/22`

I am not able to understand the output or maybe I am using an incorrect function. Please let me know if this is a real issue or just my misunderstanding.

My requirement is to remove all the overlaps in a list of IPAddresses and return the non-overlapping IPAddresses.

**Comment by prateekbansal** [comment]
Apparently, the issue is with the `second` IPAddress where `10.1.149.0/23`results in the range being treated as /32. It looks like this [doc] (https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#check-if-subnet-contains-address-or-subnet) explains it.

**Comment by seancfoley** [comment]
It is indeed the 149 that is preventing it from being treated like a block of addresses, it would have to be 148.

[Just use toPrefixBlock](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment-and-Matching-Checks#containment-within-the-enclosing-cidr-prefix-block) if you want to be sure to get the CIDR block.  

To get output like "10.1.130-250.0/23", use mergeToSequentialBlocks, which also merges the blocks but the result will not be converted to a list of CIDR blocks.  It will also drop the prefix length though, giving you 10.1.130-250.*, so to get the prefix length back use  assignMinPrefixForBlock():

	final IPAddress first = new IPAddressString("10.1.150-250.0/23").getAddress().toPrefixBlock();
	final IPAddress second = new IPAddressString("10.1.130-149.0/23").getAddress().toPrefixBlock();
	final IPAddress[] merged = first.mergeToSequentialBlocks(second);
	for (IPAddress ipAddress : merged) {
		System.out.println(ipAddress.assignMinPrefixForBlock().toConvertedString()); //10.1.130-250.0/23
	}

**Comment by prateekbansal** [comment]
thx @seancfoley! That really helped. Your library is very useful!
