### ISSUE TITLE
Iterate the IPv6 address range

### ISSUE THREAD

**Issue by wgjowen** [seancfoley/IPAddress#6]
I recently parse IPv6 address section to get all the IPv6 addresses in the section. But I came across a problem. Here is the code:
`

            IPAddress testAddress = new IPAddressString("2401:b180:1:4:f000::/120").getAddress();
            for (IPAddress ipv6AddressIter : testAddress.getIterable()) {
                System.out.println(ipv6AddressIter.toCompressedString());
            }`
I get addresses from 2401:b180:1:4:f000::/120 to 2401:b180:1:4:f0ff::/120, But I want to get the exact address without prefix, so I change the code to the following:
` 

            IPAddress testAddress = new IPAddressString("2401:b180:1:4:f000::/120").getAddress();
            for (IPAddress ipv6AddressIter : testAddress.getIterable()) {
                System.out.println(ipv6AddressIter.removePrefixLength().toCompressedString());
            }`
But out of expectation, I get 256 same addresses which are all 2401:b180:1:4:f000::

So I change to IPAddress from 4.2.0 to 3.0.0, now I can get all the address from 2401:b180:1:4:f000:: to 2401:b180:1:4:f000::ff.

Does anyone know what is the problem?

**Comment by seancfoley** [comment]
I believe this is likely because of the way removePrefixLength works, it typically zeroes out the host bits that were beyond the prefix.  There is a removePrefixLength with boolean argument that does not have that behaviour, so you can try:

    IPAddress testAddress = new IPAddressString("2401:b180:1:4:f000::/120").getAddress();
        for (IPAddress ipv6AddressIter : testAddress.getIterable()) {
            System.out.println(ipv6AddressIter.removePrefixLength(**false**).toCompressedString());
        }`

**Comment by seancfoley** [comment]
Just tried that out and it worked for me, just use removePrefixLength(false) like in my code blurb in the previous comment.  

    2401:b180:1:4:f000::
    2401:b180:1:4:f000::1
    2401:b180:1:4:f000::2
    ...
    2401:b180:1:4:f000::fe
    2401:b180:1:4:f000::ff

Reopen this if it is not exactly what you want.

**Comment by wgjowen** [comment]
Another question is the behavior of method _toCompressedString_  is different between version 3.0.0 and 4.2.0. As of version 3.0.0, _toCompressedString_ returns all the addresses **without** prefix, but _toCompressedString_ returns addresses **with** prefix as version 4.2.0. Is that a bug?

**Comment by seancfoley** [comment]
If I recall it is the iterator that may have changed.  I do not recall toCompressedString having changed, but the iterator was changed at some point in time, if I recall correctly, to retain the prefix length, I thought there may be cases where the user may wish to retain the prefix length.

If you have a code example of a change in behaviour for toCompressedString which does not involve the iterator, then please provide for me to take a look.  There can be a few changes in behaviour from one major version to the next but in such cases I always make it possible to regain the old behaviour without major changes to the code.

One more thing about the previous answer, you can also just remove the prefix length from the original address, like so:

    IPAddress testAddress = new IPAddressString("2401:b180:1:4:f000::/120").getAddress().removePrefixLength(false);
        for (IPAddress ipv6AddressIter : testAddress.getIterable()) {
            System.out.println(ipv6AddressIter.toCompressedString());
        }`

**Comment by kkrugler** [comment]
Hi @seancfoley - thanks so much for this amazing library! One bit of feedback...it would be great to add the above bit of code (updated to use `.withoutPrefixLength()`) to the code examples, as I think it's a pretty common thing to get data of the form `1.186.0.0/15`, and want to generate all addresses in that subnet.

**Comment by seancfoley** [comment]
hi @kkrugler - this is basically [this example](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-3:-Subnetting-and-Other-Subnet-Operations#iterate-through-subnet).  But I suppose I can add a small bit about dropping the prefix length and/or [generating the full subnet when not a zero host](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#to-get-just-the-prefix-block-subnet).
