### ISSUE TITLE
How to subnet IPv6 network?

### ISSUE THREAD

**Issue by micobarac** [seancfoley/IPAddress#67]
I've been trying to find in the way in the examples how to subnet IPv6 network into smaller ones, but I cannot get it right...

Initial network: `2001:4bca:1:d7d::/56`
Resulting network: `2001:4bca:1:d7d::/60`

The resulting subnets should be:

`['2001:4bca:0001:0d7d:0000:0000:0000:0000/60', '2001:4bca:0001:0d8d:0000:0000:0000:0000/60', '2001:4bca:0001:0d9d:0000:0000:0000:0000/60', '2001:4bca:0001:0dad:0000:0000:0000:0000/60', '2001:4bca:0001:0dbd:0000:0000:0000:0000/60', '2001:4bca:0001:0dcd:0000:0000:0000:0000/60', '2001:4bca:0001:0ddd:0000:0000:0000:0000/60', '2001:4bca:0001:0ded:0000:0000:0000:0000/60', '2001:4bca:0001:0dfd:0000:0000:0000:0000/60', '2001:4bca:0001:0e0d:0000:0000:0000:0000/60', '2001:4bca:0001:0e1d:0000:0000:0000:0000/60', '2001:4bca:0001:0e2d:0000:0000:0000:0000/60', '2001:4bca:0001:0e3d:0000:0000:0000:0000/60', '2001:4bca:0001:0e4d:0000:0000:0000:0000/60', '2001:4bca:0001:0e5d:0000:0000:0000:0000/60', '2001:4bca:0001:0e6d:0000:0000:0000:0000/60']`

**Comment by seancfoley** [comment]
Firstly, you have to be sure you are working [with a prefix block](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#to-get-just-the-prefix-block-subnet), which you are not in this case.  As you can see in your list of results, all your resulting subnets have bits 60 to 64 as "d".  So you're actually listing an individual address in each of the /60 blocks, not a bunch of /60 blocks.  Same goes with the /56 block.

Using toBinaryString can help identify if you have a host of zero.  Or toPrefixBlock().

Once you have that, you can [split up those addresses](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-3:-Subnetting-and-Other-Subnet-Operations#break-a-cidr-prefix-block-into-direct-component-blocks) into smaller blocks.

You can use the prefixBlockIterator or prefixBlockStream functions.
```java
IPAddress addr = new IPAddressString("2001:4bca:1:d7d::/56").getAddress();
IPAddress res = new IPAddressString("2001:4bca:1:d7d::/60").getAddress();
System.out.println(addr);
System.out.println(res);
addr = addr.toPrefixBlock();
res = res.toPrefixBlock();
System.out.println("blocks are");
System.out.println(addr.toPrefixBlock());
System.out.println(res.toPrefixBlock());
		
System.out.println("\nBreaking up " + addr);
Integer prefixLength = addr.getNetworkPrefixLength();
IPAddress newAddr = addr.setPrefixLength(prefixLength + 4, false);
Iterator<? extends IPAddress> iter = newAddr.prefixBlockIterator();
while(iter.hasNext()) {
	System.out.println(iter.next());
}
```
```
2001:4bca:1:d7d::/56
2001:4bca:1:d7d::/60
blocks are
2001:4bca:1:d00::/56
2001:4bca:1:d70::/60

Breaking up 2001:4bca:1:d00::/56
2001:4bca:1:d00::/60
2001:4bca:1:d10::/60
2001:4bca:1:d20::/60
2001:4bca:1:d30::/60
2001:4bca:1:d40::/60
2001:4bca:1:d50::/60
2001:4bca:1:d60::/60
2001:4bca:1:d70::/60
2001:4bca:1:d80::/60
2001:4bca:1:d90::/60
2001:4bca:1:da0::/60
2001:4bca:1:db0::/60
2001:4bca:1:dc0::/60
2001:4bca:1:dd0::/60
2001:4bca:1:de0::/60
2001:4bca:1:df0::/60
```

**Comment by micobarac** [comment]
@seancfoley thanks a lot! :D

**Comment by micobarac** [comment]
I have a null pointer exception problem with implementing the suggested code:

![image](https://user-images.githubusercontent.com/16001837/123376290-8c3dde00-d58a-11eb-96c2-e0314abbdc10.png)
