### ISSUE TITLE
Comparison of IPAddressRange ignores subnet

### ISSUE THREAD

**Issue by RKInnovalor** [seancfoley/IPAddress#69]
When creating a new IPAddressRange `new IPAddressString(string).getAddress()` using the following strings: "1.2.3.4/0" and "1.2.3.4/16" and calling .equals to compare them, the call returns as true - even though these two ranges have different subnets.

I think it is due to the hashCode() method in inet.ipaddr.Address only gets the hashcode of the section, and compares using this hashcode.

**Comment by seancfoley** [comment]
That is by [design](https://seancfoley.github.io/IPAddress/ipaddress.html#prefix-length-and-equality). 

Regardless of how the address may be organized into one more subnets, it is the same address. The subnet provides context, but it's the same address.  "1.2.3.4/0" and "1.2.3.4/16" are both "1.2.3.4".

It would be hard to justify an address not being equal to itself.

Also, equality follows the general recommendation in Java that [equal objects have compareTo == 0](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#compare-T-T-)

However, just like any comparison in Java, if you would prefer to use something other than the default comparator, you are free to do so.

```java
String strs[] = new String[] {
		"1.2.3.4/16",
		"1.2.3.4",
		"1.2.3.4/24",
		"1.2.3.4/32",
		"1.2.3.5/32",
		"1.2.3.5/16",
		"1.2.3.5/24",
		"1.2.3.5",	
};
List<IPAddress> addresses = new ArrayList<>(strs.length);
for(String str: strs) {
	addresses.add(new IPAddressString(str).getAddress());
}
addresses.sort(null); // default comparator
System.out.println(addresses);
Comparator<Integer> prefixComparator = new Comparator<Integer>() {
	@Override
	public int compare(Integer o1, Integer o2) {
		if(o1 != o2) {
			return o1 == null ? -1 : (o2 == null ? 1 : o1.compareTo(o2));
		}
				return 0;
	}
};
Comparator<IPAddress> comparator = new Comparator<IPAddress>() {
	@Override
	public int compare(IPAddress o1, IPAddress o2) {
		int cmp = o1.compareTo(o2);
		if(cmp == 0) {
			return prefixComparator.compare(o1.getPrefixLength(), o2.getPrefixLength());
		}
		return cmp;
	}
};
addresses.sort(comparator); // comparator that uses prefix length
System.out.println(addresses);
```
Output:
[1.2.3.4/16, 1.2.3.4, 1.2.3.4/24, 1.2.3.4/32, 1.2.3.5/32, 1.2.3.5/16, 1.2.3.5/24, 1.2.3.5]
[1.2.3.4, 1.2.3.4/16, 1.2.3.4/24, 1.2.3.4/32, 1.2.3.5, 1.2.3.5/16, 1.2.3.5/24, 1.2.3.5/32]

It is possible you are confused about addresses vs subnets.  If that is the case, see [here](https://github.com/seancfoley/IPAddress/issues/57).  1.2.3.4/16 is not a subnet, it is a single address.

**Comment by RKInnovalor** [comment]
Thanks for your advice, Yes I was confused about addresses vs subnets. For anyone else finding this issue, this wiki article really helped: https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#IPv4_CIDR_blocks
