### ISSUE TITLE
iterate IPAddress.getIterable is taking more than 20 seconds

### ISSUE THREAD

**Issue by vamsikrishnanekkalapudi** [seancfoley/IPAddress#7]
**Note:** This is not a bug just performance issue. 

Following method return list of IP address from wild card string `10.*.*.*` and i have added the println statements to know the time it is taking to iterate IPAddress ,
```
public List<String> getIPAddressListFromWildCard(String hostAddress)throws AddressStringException,IncompatibleAddressException {
		List<String> listIPAddress = new ArrayList<String>();
		IPAddressString ipAddressString = new IPAddressString("10.*.*.*");
		try {
			IPAddress hostAddressObj = ipAddressString.toAddress();
			System.out.println("count: "+hostAddressObj.getCount());
			System.out.println("date at before start iterator "+new Date());
			for(IPAddress address:hostAddressObj.getIterable()) {
				listIPAddress.add(address.toSubnetString());
			}
			System.out.println("date at after completion of iterator "+new Date());
		} catch (AddressStringException | IncompatibleAddressException e) {
			throw e;
		}
		return listIPAddress;
	}
```

**Response**

count: 16777216
date at before start iterator Mon Sep 03 11:54:53 IST 2018
date at after completion of iterator Mon Sep 03 11:55:19 IST 2018

Here to iterate IPAddress, it is taking more than 20 seconds.Is there any way to get the list of IP addresses without iterating.I just need list of IP addresses not the IPAddress object of each IP .

**Comment by seancfoley** [comment]
Yes, it does take a bit of time to get through 16 million addresses.  

On my laptop your code takes about 8 seconds.

You can probably skip the parsing entirely with this particular test, if the addresses will always be ending in wildcards like `10.*.*.*`, like this:

    IPAddress hostAddressObj = ipAddressString.toAddress();
    IPv4Address ipv4Addr = hostAddressObj.toIPv4();
    int val = ipv4Addr.getLower().intValue();
    int highVal = ipv4Addr.getUpper().intValue();
    while(val <= highVal) {
        IPv4Address ip = new IPv4Address(val++);
        listIPAddress.add(ip.toSubnetString());
    }

However, that code only shaved off 1 second of the 8 seconds for me, getting it down to 7 seconds.  Additionally, that code uses integer to iterate (lowVal) which only works with IPv4, to make it more general to work with IPv6 you'd need to use a pair of long values or BigInteger instead.

Another option is to use a method that creates a string directly, the IPv4Address.toNormalizedString method.

    IPAddress hostAddressObj = ipAddressString.toAddress();
    IPv4Address ipv4Addr = hostAddressObj.toIPv4();
    int highVal = ipv4Addr.getUpper().intValue();
    class ValueProvider implements SegmentValueProvider {
        int val = ipv4Addr.getLower().intValue();
				
        @Override
        public int getValue(int segmentIndex) {
            return 0xff & (val >>> ((3 - segmentIndex) << 3));
        }
    }
    ValueProvider prov = new ValueProvider();
    while(prov.val <= highVal) {
        String s = IPv4Address.toNormalizedString(IPv4Address.defaultIpv4Network(), prov, prov, null);
        listIPAddress.add(s);
        prov.val++;
    }

For me, this sliced the time in half, down to 4 seconds.

The list itself is taking some of the time, which you can alleviate by giving it a large initial capacity: List<String> listIPAddress = new ArrayList<String>(17000000);
However for me this had little effect.

Beyond this, I think perhaps modifying IPv4Address.toNormalizedString to reuse the same StringBuilder object may be beneficial to lowering the time further, so I'll look into that.

**Comment by vamsikrishnanekkalapudi** [comment]
Thank you for quick response.
I need to support both IPV4 and IPV6 versions and also this iterator issue i am facing for range and subnet mask and wildcard. 

When i call hostAddressObj.getCount() method it is giving number of targeted IP addresses with out any delay.But when i iterate to fetch list of targeted IP's it's taking some time.

**Comment by seancfoley** [comment]
To the latest release 5.0 I added two static toNormalizedString methods in the IPAddress class.

The intent was to be able to produce standard address strings without creating any intervening IPAddress objects, and also to create such strings with an existing StringBuilder instance.

I tried it by running the following block of  code where valProvider is an instance of IPAddressValueProvider:
	
	IPAddressString ipAddressString = new IPAddressString("10.*.*.*");
	IPAddress hostAddressObj = ipAddressString.gertAddress();
	MyValProvider valProvider = new MyValProvider();
	StringBuilder builder = new StringBuilder();
	do {
		IPAddress.toNormalizedString(valProvider, builder);
		listIPAddress.add(builder.toString());
		builder.setLength(0);
	} while(valProvider.increment());

In this case I used the following class for the IPAddressValueProvider implementation, allowing me to increment the address values efficiently.

    class MyValProvider implements IPAddressValueProvider {
			
	private AbstractValueProvider valProvider;
				
	abstract class AbstractValueProvider implements SegmentValueProvider {
		abstract boolean increment();
	}
				 
	MyValProvider() {
		if(hostAddressObj.isIPv4()) {
			valProvider = new AbstractValueProvider() {
				int val = hostAddressObj.toIPv4().getLower().intValue();
				int upperVal = hostAddressObj.toIPv4().getUpper().intValue();
							
				@Override
				public int getValue(int segmentIndex) {
					return 0xff & (val >>> ((3 - segmentIndex) << 3));
				}
							
				@Override
				boolean increment() {
					return val++ != upperVal;
				}
			};
		} else if(hostAddressObj.isIPv6()) {
			IPv6Address addr = hostAddressObj.toIPv6();
			byte bytes[] = addr.getBytes();
			long hv = (bytes[0] << 24) | (bytes[1] << 16) | (bytes[2] << 8) | bytes[3];
			long lv = (bytes[4] << 24) | (bytes[5] << 16) | (bytes[6] << 8) | bytes[7];
			bytes = addr.getUpperBytes();
			long uhv = (bytes[0] << 24) | (bytes[1] << 16) | (bytes[2] << 8) | bytes[3];
			long ulv = (bytes[4] << 24) | (bytes[5] << 16) | (bytes[6] << 8) | bytes[7];
						
			valProvider = new AbstractValueProvider() {
				long lowVal = lv, highVal = hv;
				long upperLowVal = ulv, upperHighVal = uhv;
							
				@Override
				public int getValue(int segmentIndex) {
					if(segmentIndex <= 3) {
						return (int) (0xffff & (highVal >>> ((3 - segmentIndex) << 4)));
					}
					return (int) (0xffff & (lowVal >>> ((7 - segmentIndex) << 4)));
				}
							
				@Override
				boolean increment() {
					boolean result = (lowVal != upperLowVal) || (highVal != upperHighVal);
					if(++lowVal == 0) {
						highVal++;
					}
					return result;
				}
			};
		}
	}
				
	boolean increment() {
		return valProvider.increment();
	}
				
	@Override
	public int getSegmentCount() {
		return hostAddressObj.getSegmentCount();
	}

	@Override
	public SegmentValueProvider getValues() {
		return valProvider;
	}

	@Override
	public IPVersion getIPVersion() {
		return hostAddressObj.getIPVersion();
	}		
    };
    MyValProvider valProvider = new MyValProvider();
			
Using this code I was able to generate individual address strings for the subnet 10.*.*.*, which is 16 million addresses, in 2 seconds rather than 6 seconds when using this simpler but less performant code:

    for(IPAddress address: hostAddressObj.getIterable()) {
        listIPAddress.add(address.toSubnetString());
    }

Both work for both IPv4 and IPv6.  So that's a substantial improvement in performance due to minimizing object creation.  I'm not so sure you can get any more efficient when producing 16 million address strings.  

For large subnets it might be better to revisit your algorithm, to produce strings in background threads or to work with subnets without generating individual strings.  With IPv6, subnets can get so large it's simply not reasonable to generate a list of addresses (there are 340 undecillion IPv6 addresses, so even terabytes of memory are insufficient to store such a list). 

However, when producing 16 million address strings this new code is now highly optimized and performant as described above.
