### ISSUE TITLE
How can I get IP addresses list by a start address and number?

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#70]
For example.I have a start address "1.1.1.1.1" and number "300".
I want to get an addresses list below:
1.1.1.1
1.1.1.2
...
1.1.1.255--->255 addresses
1.1.2.0
1.1.2.1
...
1.1.2.44--->another 45 addresses

If the number exceeds the maximum address "255.255.255.255", get the maximum usable address of number.

**Comment by seancfoley** [comment]
There are two options, either use increment(1) each time to get to 300, or the better option is to y = x.increment(300), then r = x.spanWithRange(y), then r.iterator()
