### ISSUE TITLE
toSequentialRange: changing between upper and lower makes no difference 

### ISSUE THREAD

**Issue by eduardpo** [seancfoley/IPAddress#76]
Hi @seancfoley,

I've noticed, while using your library & calling "toSequentialRange", that changing between "upper" and "lower" and vise versa, makes no difference.
Is it an expected behavior? 

### scenario:
String IPAddressStart = "192.168.0.1;
String IPAddressEnd = "192.168.0.7;

IPAddress lower = new IPAddressString(IPAddressStart).toAddress();
IPAddress upper = new IPAddressString(IPAddressEnd).toAddress();

IPAddressSeqRange ipSeqRange = lower.toSequentialRange(upper);
System.out.println("IP range: " + ipSeqRange + " counts: | " + ipSeqRange.getCount().intValue());

IPAddressSeqRange ipSeqRange = upper.toSequentialRange(lower);
System.out.println("IP range: " + ipSeqRange + " counts: | " + ipSeqRange.getCount().intValue());

### output: 
IP range: 192.168.0.1 -> 192.168.0.7 | counts: 7
IP range: 192.168.0.1 -> 192.168.0.7 | counts: 7

Thanks,
Ed

**Comment by eduardpo** [comment]
I see, it was not intuitive for me :)
Anyway, i've tried to make use of this method to test our project requirement, which does not permit lower & upper to be interchangeable, can i still use your library for this purpose without looking for workaround? 

Thanks,
Ed

**Comment by seancfoley** [comment]
I don't know what you mean by "does not permit".  I really don't know what operations you need or want.  If you want to track a start and an end, just wrap:
```java
public class YourOrderedRange {
	private IPAddress first, last; // first is lower or upper in range, last is the opposite
	private IPAddressSeqRange range;
	 
	public YourOrderedRange(IPAddress first, IPAddress last) {
		this.first = first;
		this.last = last;
		this.range = first.spanWithRange(last);
	}
	
	// add whatever operations you need
}
```

**Comment by eduardpo** [comment]
Unfortunately it does not help,
In general, we need to make sure that defined "upper" is higher sequentially than the "lower" one...

**Comment by seancfoley** [comment]
That is how the IPAddressSeqRange works, the upper is always higher sequentially.

**Comment by seancfoley** [comment]
I am closing this because you have not stated what you want to achieve, nor have you stated some requirement or some desired feature that is not addressed by this library.
