### ISSUE TITLE
How to get count of an IP address?This IP address may be singel or CIDR or Range format.

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#77]
How to get count of an IP address?This IP address may be singel or CIDR or Range format.

**Comment by seancfoley** [comment]
Use the getCount() method [as shown here](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#get-prefix-length-network-mask-network-address-version-subnet-size-and-segments-from-CIDR-address-or-subnet)
