### ISSUE TITLE
IPAddress.contains() for IpV6 is not working

### ISSUE THREAD

**Issue by nsamoylov** [seancfoley/IPAddress#78]
I got this example running:

        IPAddressString one = new IPAddressString("2001:1900:2100::5ad0/120");
        IPAddressString two = new IPAddressString("2001:1900:2100::5ad4/126");
        System.out.println(one +  " contains " + two + " " + one.contains(two));
       

Results:
2001:1900:2100::5ad0/120 contains 2001:1900:2100::5ad4/126 false

Expected: 
2001:1900:2100::5ad0/120 contains 2001:1900:2100::5ad4/126 true

I assume that this is the reason that longestPrefixMatchNode("2001:1900:2100::5ad0/120") does not find "2001:1900:2100::5ad4/126" on the following trie either:

● ::/0 = aggregate,internal_agg (5)
└─○ 2001::/17 = null (4)
  ├─○ 2001::/19 = null (3)
  │ ├─● 2001:450::/32 = aggregate,internal_agg (1)
  │ └─● 2001:1900::/32 = aggregate,internal_agg (2)
  │   └─● 2001:1900:2100::5ad4/126 = connected,live (1)
  └─● 2001:4c08::/32 = aggregate,internal_agg (1)

**Comment by seancfoley** [comment]
Hello.  This is a common misconception.  If you want to get a prefix block CIDR subnet, you have to do one of two things:

1.  specify an address with a host of zero
```java
IPAddressString one = new IPAddressString("2001:1900:2100::5a00/120");
IPAddressString two = new IPAddressString("2001:1900:2100::5ad4/126");
System.out.println(one +  " contains " + two + " " + one.contains(two));
```
2. or use the method toPrefixBlock() to convert an address to its enclosing prefix block CIDR subnet
```java
IPAddress one = new IPAddressString("2001:1900:2100::5ad0/120").getAddress().toPrefixBlock(); // 2001:1900:2100::5a00/120
IPAddress two = new IPAddressString("2001:1900:2100::5ad4/126").getAddress();
System.out.println(one +  " contains " + two + " " + one.contains(two));
```
2001:1900:2100::5ad0/120 is just a single address, 2001:1900:2100::5a00/120 is a subnet

This is very similar to #26, issue #30, issue #40, issue #45, issue #51, issue #54, issue #57, issue #71, and also similar to issue #39 and issue #53.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address).
