### ISSUE TITLE
Bounds don't work properly

### ISSUE THREAD

**Issue by kbluue** [seancfoley/IPAddress#80]
![image](https://user-images.githubusercontent.com/7539597/142611988-f6029843-760f-4750-ae3c-9695024a8f31.png)
The above is from v3.0.0

![image](https://user-images.githubusercontent.com/7539597/142611865-a0831379-b01c-4271-b938-6f6f8a6ec65d.png)
This is from v5.0.0

As you can see, the bounds functions are not working properly. 

Thanks.

**Comment by kbluue** [comment]
Forgive me. This was a case of READ **ALL** THE DOCS

Found the configuration in the [v4 docs](https://seancfoley.github.io/IPAddress/v4/#_Prefix_Length_Handling).

`MACAddressNetwork.setDefaultPrefixConfiguration(PrefixConfiguration.ALL_PREFIXED_ADDRESSES_ARE_SUBNETS);
IPv4AddressNetwork.setDefaultPrefixConfiguration(PrefixConfiguration.ALL_PREFIXED_ADDRESSES_ARE_SUBNETS);
IPv6AddressNetwork.setDefaultPrefixConfiguration(PrefixConfiguration.ALL_PREFIXED_ADDRESSES_ARE_SUBNETS);`

**Comment by seancfoley** [comment]
The best way to get what you want is to use the method 'toPrefixBlock'. This is similar to issue 78.

The configuration options you listed are intended for backwards compatibility and will likely be removed in a future version.

This is explained in [this wiki entry](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Checking-Host-Address-Subnet,-Extracting-Address-Subnet-Info#parse-ip-address-string-with-prefix-length-as-subnet-or-ip-address).

**Comment by seancfoley** [comment]
```java
IPAddressString string = new IPAddressString("1.1.1.17/24");
IPAddress addr = string.getAddress().toPrefixBlock();
String str = String.format("%s - upper bound %s // lower bound %s", addr, addr.getUpper(), addr.getLower());
System.out.println(str);
```
```
1.1.1.0/24 - upper bound 1.1.1.255/24 // lower bound 1.1.1.0/24
```
