### ISSUE TITLE
Get index of address in network/mask

### ISSUE THREAD

**Issue by robross0606** [seancfoley/IPAddress#9]
I looked through the API and don't see anything specifically available to quickly do this, though I'm sure it is possible via the low-level (fast) math or high-level (slow) iterators.  Using your API and a given subnet/mask (IPv4AddressNetwork class?), how would you recommend getting hold of an actual subnet (if possible) which holds this address and the index (again, if possible) of that address within the subnet?

As a simple contrived example:
```
Subnet/Mask = 192.168.1.0/24
Address = 192.168.4.20
Expected answers:  1) 192.168.4.0/24
                   2) 19
```

I'm quite aware that the example address does not exist inside this example subnet.  This was done on purpose to see if the API has a way to give you a set of the possible (i.e scale range) subnets given a mask, and then use those possible subnets to determine which one would include the simple address (note no provided mask on purpose).

It may be that the simplest approach here is the bitwise math, but I wanted to see if your API has some hidden features I didn't notice.  If possible, I'd also be interested in having the index be dependent upon whether you wanted to consider just the host range.

Thanks!

**Comment by seancfoley** [comment]
The one part of your question that is not clear to me is what you mean by the set of "possible" subnets given a mask or an existing subnet?  You use the term "scale-range" but I am not certain what that means exactly.  Anyway, I will see if I can answer your questions.  

The API can tell you whether an address 192.168.4.20 is inside a subnet 192.168.1.0/24 (using "contains").  In your example this would return false.  

	IPAddress subnet = new IPAddressString("192.168.1.0/24").getAddress();
	IPAddress address = new IPAddressString("192.168.4.20").getAddress();
	boolean contains = subnet.contains(address); //false
	
From there you say you wish to know what subnets would contain address, perhaps you mean a subnet with the same prefix length / mask (24 / 255.255.255.0).  

One way of doing this is to simply apply a prefix length to the address. To make this "similar" to the original subnet I suppose you might choose the same prefix length / mask as the original address.

	int subnetPrefixLength = subnet.getPrefixLength(); //24
	IPAddress matchingSubnet = address.setPrefixLength(subnetPrefixLength).toPrefixBlock();
	System.out.println(matchingSubnet); //192.168.4.0/24
	contains = matchingSubnet.contains(address);
	System.out.println(contains); //true

Now, whether this answers your question I am unsure.  You may be looking for something a bit more elaborate.  It is also possible, given an existing subnet, to shift the prefix length in an attempt to find other subnets that are "near".  

	IPAddress containingBlock = findBlock(subnet, address);

	static IPAddress findBlock(IPAddress subnet, IPAddress address) {
		System.out.println("trying 1 block from " + subnet);
		if(subnet.contains(address)) {
			return subnet;
		}
		int subnetPrefixLength = subnet.getPrefixLength();
		IPAddress containingBlock;
		int shiftedPrefixLength = subnetPrefixLength;
		top:
		while(true) {
			IPAddress shiftedBlock = subnet.setPrefixLength(--shiftedPrefixLength).toPrefixBlock();
			IPAddress blocks = shiftedBlock.setPrefixLength(subnetPrefixLength, false);
			System.out.println("trying " + blocks.getPrefixCount() + " blocks from " + shiftedBlock);
			Iterator<? extends IPAddress> blocksIterator = blocks.prefixBlockIterator();
			while(blocksIterator.hasNext()) {
				containingBlock = blocksIterator.next();
				System.out.println("checking if " + containingBlock + " contains " + address);
				if(containingBlock.contains(address)) {
					break top;
				}
			}
		}
		System.out.println("Found containing block " + containingBlock);
		return containingBlock;
	}

The output is:

	trying 1 block from 192.168.1.0/24
	trying 2 blocks from 192.168.0.0/23
	checking if 192.168.0.0/24 contains 192.168.4.20
	checking if 192.168.1.0/24 contains 192.168.4.20
	trying 4 blocks from 192.168.0.0/22
	checking if 192.168.0.0/24 contains 192.168.4.20
	checking if 192.168.1.0/24 contains 192.168.4.20
	checking if 192.168.2.0/24 contains 192.168.4.20
	checking if 192.168.3.0/24 contains 192.168.4.20
	trying 8 blocks from 192.168.0.0/21
	checking if 192.168.0.0/24 contains 192.168.4.20
	checking if 192.168.1.0/24 contains 192.168.4.20
	checking if 192.168.2.0/24 contains 192.168.4.20
	checking if 192.168.3.0/24 contains 192.168.4.20
	checking if 192.168.4.0/24 contains 192.168.4.20
	Found containing block 192.168.4.0/24

For the second part of your question, this is a value subtraction.  There is an "increment" method for adding a long to an address to get a second address, but you are looking for the reverse, getting the "increment" given the two addresses, which has no currently dedicated method, but is easy enough anyway converting to values for each address (one line of code).

That second block of code in the method getIndex works for ipv6 and ipv4, if you are just using ipv4 you can stick to longs as shown int the first block.

	getIndex(containingBlock, address);

	static void getIndex(IPAddress containingBlock, IPAddress address) {
		if(address.isIPv4()) {
			long longIndex = address.toIPv4().longValue() - containingBlock.toIPv4().getLowerNonZeroHost().longValue();
			System.out.println("index is " + longIndex);
		} else {
			BigInteger index = address.getValue().subtract(containingBlock.getLowerNonZeroHost().getValue());
			System.out.println("index is " + index);
		}
	}

The output is:

    index is 19
