### ISSUE TITLE
 Address intersection identification

### ISSUE THREAD

**Issue by Shankiss** [seancfoley/IPAddress#91]
Two address lists A and B, how to quickly determine that the address in the B list is within the range of the A address list and print the address

**Comment by seancfoley** [comment]
Can you describe what you mean by "the range of the A address list"?  Perhaps you might provide an example?

**Comment by seancfoley** [comment]
If the addresses in list A were CIDR subnets or individual addresses, and you wanted to know if an address in list B were contained by any of the subnets in list A, then you could use [this example](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-2:-Subnet-Containment,-Matching,-Comparing#select-cidr-prefix-block-subnets-containing-an-address).

But I'm not entirely sure that's what you're asking.

**Comment by Shankiss** [comment]
> Can you describe what you mean by "the range of the A address list"? Perhaps you might provide an example?
List<String> listA = new ArrayList<>();
listA.add("103.42.76.0/24");
listA.add("111.30.182.128/25");
listA.add("221.181.97.128/25");

List<String> listB = new ArrayList<>(); 
listB.add("103.42.76.33/32");
listB.add("103.42.76.103/32");
listB.add("111.30.182.211/32");
listB.add("120.221.25.23/30");
listB.add("117.187.129.203/29");

For example, the above-mentioned address list A and list b. There is no intersection between all CIDR blocks and a single address in A, and there is no intersection between all CIDR blocks and a single address in B. I want to get the CIDR block and single address contained in list A in list B. The expected result of the above example is:
103.42.76.33/32, 103.42.76.103/32, 111.30.182.211/32

From your code example, I know it can be satisfied in this way:
List<IPAddress> blocks = new ArrayList<>();
for (String str : listA) {
     blocks.add(new IPAddressString(str).getAddress());
}

IPv4AddressTrie ipv4AddressTrie = new IPv4AddressTrie();
for (IPAddress block : blocks) {
      ipv4AddressTrie.add(block.toIPv4());
}

listB.stream().forEach(item -> {
     IPAddressString toFindAddrStr = new IPAddressString(item);
     IPv4Address toFindBlockFor = toFindAddrStr.getAddress().toIPv4();
     if (ipv4AddressTrie.elementContains(toFindBlockFor)) {
            System.out.println(toFindBlockFor.toString());
      }
});
But this method needs to loop through list B. I would like to get your help. Is there a more efficient way to satisfy it, such as creating a tree for both list A and list B, and comparing the two trees?

**Comment by Shankiss** [comment]
List listA = new ArrayList<>();
listA.add("103.42.76.0/24");
listA.add("111.30.182.128/25");
listA.add("221.181.97.128/25");

List listB = new ArrayList<>();
listB.add("103.42.76.33/32");
listB.add("103.42.76.103/32");
listB.add("111.30.182.211/32");
listB.add("120.221.25.23/30");
listB.add("117.187.129.203/29");

For example, the above-mentioned address list A and list b. There is no intersection between all CIDR blocks and a single address in A, and there is no intersection between all CIDR blocks and a single address in B. I want to get the CIDR block and single address contained in list A in list B. The expected result of the above example is:
103.42.76.33/32, 103.42.76.103/32, 111.30.182.211/32

From your code example, I know it can be satisfied in this way:
List blocks = new ArrayList<>();
for (String str : listA) {
blocks.add(new IPAddressString(str).getAddress());
}

IPv4AddressTrie ipv4AddressTrie = new IPv4AddressTrie();
for (IPAddress block : blocks) {
ipv4AddressTrie.add(block.toIPv4());
}

listB.stream().forEach(item -> {
IPAddressString toFindAddrStr = new IPAddressString(item);
IPv4Address toFindBlockFor = toFindAddrStr.getAddress().toIPv4();
if (ipv4AddressTrie.elementContains(toFindBlockFor)) {
System.out.println(toFindBlockFor.toString());
}
});
But this method needs to loop through list B. I would like to get your help. Is there a more efficient way to satisfy it, such as creating a tree for both list A and list B, and comparing the two trees?

**Comment by seancfoley** [comment]
I am not aware of a way to compare two tries in a manner that is more efficient (ie scales better) than the code above.  The code is O(m+n) where m and n are the sizes of the two lists.  This is more efficient than comparing every element in the first list with every element in the other, which is O(mn).  However, I think it's unlikely you can do better than O(m+n), I'd guess that any algorithm would need to be at least proportional to the number of elements in the two lists.

I'd also note that your code is not quite right if you want to find all intersections, you need to check for both containing and contained blocks in the trie to find all intersections:
```java
if (ipv4AddressTrie.elementContains(toFindBlockFor) || ipv4AddressTrie.elementsContainedBy(toFindBlockFor) != null) {
    System.out.println(toFindBlockFor.toString());
}
```

**Comment by Shankiss** [comment]
Thanks for your answer. I also want to ask a question。
`if (ipv4AddressTrie.elementsContaining(toFindBlockFor) != null || ipv4AddressTrie.elementsContainedBy(toFindBlockFor) != null) {
    System.out.println(toFindBlockFor.toString());
}`
Is this code also satisfying to find all intersections？

**Comment by seancfoley** [comment]
The answer to your question is yes.

**Comment by Shankiss** [comment]
thanks~
