### ISSUE TITLE
Can I ask a question about the numeric IP address and the format introduction of various IP addresses?

### ISSUE THREAD

**Issue by angelyouyou** [seancfoley/IPAddress#94]
1.IP address format
Is there any introduction about various IP address formats(so powerful and so many)? I can't find the document in the [link](https://seancfoley.github.io/IPAddress/). In our business, we want to support only certain types of IP address input, but we don't know how to customize it (although there are many functions starting with "allow_", we don't know the exact customization effect) .

2.Numeric IP address check question(Both of below are assert failed):

```
 public boolean isIPv4CIDRAddrBlock(String ipAddrStr) {
        IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
                allowEmpty(false).
                allowIPv4(true).
                allowIPv6(false).
                allowPrefixOnly(true).setRangeOptions(AddressStringParameters.RangeParameters.NO_RANGE).
                allowMask(false).
                allow_inet_aton(false).
                allowAll(false).
                allowPrefixOnly(true).
                toParams();

        return (checkHostIdentifierString(new IPAddressString(ipAddrStr, strParams)) && (!isIPv4Address(ipAddrStr)));
    }

assertFalse(isIPv4CIDRAddrBlock("2"));
```
-->assert failed

```
public static boolean isIPv6CIDRAddrBlock(String ipAddrStr) {
        IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
                allowEmpty(false).
                allowIPv4(false).
                allowIPv6(true).
                allowPrefixOnly(true).setRangeOptions(AddressStringParameters.RangeParameters.NO_RANGE).
                allowMask(false).
                allow_inet_aton(false).
                allowAll(false).
                allowPrefixOnly(true).
                toParams();

        return (checkHostIdentifierString(new IPAddressString(ipAddrStr, strParams)) && !isIPv6Address(ipAddrStr));
    }

assertFalse(isIPv6CIDRAddrBlock("2"));
```

**Comment by seancfoley** [comment]
**Question 1:**  I don't think there is anything more than the javadoc.  You'd have to rely on what is in the javadoc.

allowEmpty: allows ""
allowIPv4: allow a format which ends up being parsed as IPv4
allowIPv6: allow a format which ends up being parsed as IPv6
allowPrefixOnly(true): allow "/32" which is just a prefix and can in some cases be interpreted as IPv4 or IPv6, in which cases it becomes the IPv4 or IPv6 mask of the given prefix length.  This is not standard so you'd probably want to disallow.
setRangeOptions: allows addresses with ranges like 1.2-3.4.5 
 allowMask: allows 1.2.3.4/255.255.0.0 which is one way of specifying a CIDR subnet
allow_inet_aton: allows IPv4 addresses with 3 segments or less like 1.2.3, or IPv4 formatted as hex or octal like 0x1.0x2.0x3.0x4.  A lot of software allows these formats.
allowAll: allows "*" which represents the full set of all IPv4 and IPv6 addresses

**Question 2:** 

Address like "2" are considered "single-segment" meaning that they do not have segment separators like "." or ":".  So you could use "allowSingleSegment".  In fact, it would be considered an inet_aton format as well, but when it comes to single-segment addresses, ["allowSingleSegment" takes precedence](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4AddressStringParameters.html#inet_aton_joinedSegments).

I would recommend something like the following, where you eliminate many possibilities and then after parsing you check the resulting address.

```java
	static IPAddress isCIDRBlock(String ipAddrStr, boolean ipv4) {
		IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
			allow_inet_aton(true).
			allowAll(false).
			allowEmpty(false).
			allowIPv4(ipv4).
			allowIPv6(!ipv4).
			allowMask(true). // do you want 1.2.0.0/255.255.0.0?
			allowPrefix(true).
			allowPrefixOnly(false).
			allowSingleSegment(false). 
			allowWildcardedSeparator(false).
            setRangeOptions(AddressStringParameters.RangeParameters.NO_RANGE). // no - or *
			getIPv4AddressParametersBuilder().
				allowBinary(false).
				allowLeadingZeros(false).
				allowPrefixesBeyondAddressSize(false).
				allowPrefixLengthLeadingZeros(false).
				allowUnlimitedLeadingZeros(false).
				getParentBuilder().
			getIPv6AddressParametersBuilder().
				allowBase85(false).
				allowBinary(false).
				allowEmptyZone(false).
				allowLeadingZeros(false).
				allowMixed(true).
				allowPrefixesBeyondAddressSize(false).
				allowPrefixLengthLeadingZeros(false).
				allowUnlimitedLeadingZeros(false).
				allowWildcardedSeparator(false).
				allowZone(false).
				getParentBuilder().
			toParams();
		IPAddressString addrStr = new IPAddressString(ipAddrStr, strParams);
		if(addrStr.isValid()) {
			IPAddress address = addrStr.getAddress();
			if(address.isPrefixBlock()) {
				// this includes single-address blocks like 1.2.3.4/32, to exclude use && address.isMultiple()
				return address;
			}
		}
		return null;
	}
	boolean isIPv4 = true;
	System.out.println(isCIDRBlock("2", isIPv4));
	System.out.println(isCIDRBlock("1.2.0.0/16", isIPv4));
	System.out.println(isCIDRBlock("1.2.3.4/16", isIPv4));
	System.out.println(isCIDRBlock("1.2.3.4/32", isIPv4));
```
Output:
```
null
1.2.0.0/16
null
1.2.3.4/32
```

**Comment by angelyouyou** [comment]
Thank you very much for your help.
In fact, we only want to support the following three formats in our project:

A single IPv4 (dot-separated decimal) or IPv6 address (colon-separated hexadecimal)
Example: 1.1.1.1, 2012::3 (or its full IPv6 address format)
IP addresses in other formats are not expected to be included.

Standard CIDR format (IP network segment/prefix and length)
For example: 1.1.1.0/24, 2012::/64 (or its full IPv6 address format)
IP addresses in other formats are not expected to be included.

Range and match segment format
For example: 1.2.., 1.2.0-255.0-255 (* and - can appear in reasonable places defined in the current library)
IP addresses in other formats are not expected to be included.


> **Question 1:** I don't think there is anything more than the javadoc. You'd have to rely on what is in the javadoc.
> 
> allowEmpty: allows "" allowIPv4: allow a format which ends up being parsed as IPv4 allowIPv6: allow a format which ends up being parsed as IPv6 allowPrefixOnly(true): allow "/32" which is just a prefix and can in some cases be interpreted as IPv4 or IPv6, in which cases it becomes the IPv4 or IPv6 mask of the given prefix length. This is not standard so you'd probably want to disallow. setRangeOptions: allows addresses with ranges like 1.2-3.4.5 allowMask: allows 1.2.3.4/255.255.0.0 which is one way of specifying a CIDR subnet allow_inet_aton: allows IPv4 addresses with 3 segments or less like 1.2.3, or IPv4 formatted as hex or octal like 0x1.0x2.0x3.0x4. A lot of software allows these formats. allowAll: allows "*" which represents the full set of all IPv4 and IPv6 addresses
> 
> **Question 2:**
> 
> Address like "2" are considered "single-segment" meaning that they do not have segment separators like "." or ":". So you could use "allowSingleSegment". In fact, it would be considered an inet_aton format as well, but when it comes to single-segment addresses, ["allowSingleSegment" takes precedence](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/ipv4/IPv4AddressStringParameters.html#inet_aton_joinedSegments).
> 
> I would recommend something like the following, where you eliminate many possibilities and then after parsing you check the resulting address.
> 
> ```java
> 	static IPAddress isCIDRBlock(String ipAddrStr, boolean ipv4) {
> 		IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
> 			allow_inet_aton(true).
> 			allowAll(false).
> 			allowEmpty(false).
> 			allowIPv4(ipv4).
> 			allowIPv6(!ipv4).
> 			allowMask(true). // do you want 1.2.0.0/255.255.0.0?
> 			allowPrefix(true).
> 			allowPrefixOnly(false).
> 			allowSingleSegment(false). 
> 			allowWildcardedSeparator(false).
> 			setRangeOptions(AddressStringParameters.RangeParameters.NO_RANGE). // no "-" or "*"
> 			getIPv4AddressParametersBuilder().
> 				allowBinary(false).
> 				allowLeadingZeros(false).
> 				allowPrefixesBeyondAddressSize(false).
> 				allowPrefixLengthLeadingZeros(false).
> 				allowUnlimitedLeadingZeros(false).
> 				getParentBuilder().
> 			getIPv6AddressParametersBuilder().
> 				allowBase85(false).
> 				allowBinary(false).
> 				allowEmptyZone(false).
> 				allowLeadingZeros(false).
> 				allowMixed(true). // like a:b:c:d:e:f:1.2.3.4
> 				allowPrefixesBeyondAddressSize(false).
> 				allowPrefixLengthLeadingZeros(false).
> 				allowUnlimitedLeadingZeros(false).
> 				allowWildcardedSeparator(false).
> 				allowZone(false).
> 				getParentBuilder().
> 			toParams();
> 		IPAddressString addrStr = new IPAddressString(ipAddrStr, strParams);
> 		if(addrStr.isValid()) {
> 			IPAddress address = addrStr.getAddress();
> 			if(address.isPrefixBlock()) {
> 				// this includes single-address blocks like 1.2.3.4/32, to exclude use && address.isMultiple()
> 				return address;
> 			}
> 		}
> 		return null;
> 	}
> 	boolean isIPv4 = true;
> 	System.out.println(isCIDRBlock("2", isIPv4));
> 	System.out.println(isCIDRBlock("1.2.0.0/16", isIPv4));
> 	System.out.println(isCIDRBlock("1.2.0.0/255.255.0.0", isIPv4));
> 	System.out.println(isCIDRBlock("1.2.3.4/16", isIPv4));
> 	System.out.println(isCIDRBlock("1.2.3.4/32", isIPv4));
> ```
> 
> Output:
> 
> ```
> null
> 1.2.0.0/16
> 1.2.0.0/16
> null
> 1.2.3.4/32
> ```

**Comment by seancfoley** [comment]
It's not entirely clear what you mean when you say you want to allow Range and widcard segment format in "reasonable places".  The concept of "reasonable" is not defined, nor is it "reasonable" to expect anyone else to know what you mean by "reasonable".  Whether you want to allow something like "1-3.0.0.0", I have no idea.  And if you do not want to allow that, then what exactly you do want, you have not stated that anywhere.  Maybe you want something like this.
```java
static IPAddress check(String ipAddrStr) {
		IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
			allow_inet_aton(true).
			allowAll(false).
			allowEmpty(false).
			allowIPv4(true).
			allowIPv6(true).
			allowMask(true). // do you want 1.2.0.0/255.255.0.0?
			allowPrefix(true).
			allowPrefixOnly(false).
			allowSingleSegment(false). 
			allowWildcardedSeparator(true).
	      setRangeOptions(AddressStringParameters.RangeParameters.WILDCARD_AND_RANGE). // no - or *
			getIPv4AddressParametersBuilder().
				allowBinary(false).
				allowLeadingZeros(false).
					allowPrefixesBeyondAddressSize(false).
					allowPrefixLengthLeadingZeros(false).
					allowUnlimitedLeadingZeros(false).
					getParentBuilder().
				getIPv6AddressParametersBuilder().
					allowBase85(false).
					allowBinary(false).
					allowEmptyZone(false).
					allowLeadingZeros(false).
			allowMixed(false).
			allowPrefixesBeyondAddressSize(false).
			allowPrefixLengthLeadingZeros(false).
			allowUnlimitedLeadingZeros(false).
			allowWildcardedSeparator(false).
			allowZone(false).
			getParentBuilder().
		toParams();
	IPAddressString addrStr = new IPAddressString(ipAddrStr, strParams);
	if(addrStr.isValid()) {
		IPAddress address = addrStr.getAddress();
		if(address.isMultiple()) {
				// whether you want to allow prefixed individual addresses, seems like you do not, but I don't know really
			if(!address.isPrefixed()) {
				return address;
			}
		} else {
			// you appear to want to allow all subnets
			return address;
		}
	}
	return null;
}
```
This seems less like an issue with this library than it is an issue with you deciding precisely what you want.  I am not interested in guessing.  Closing.
