### ISSUE TITLE
Is there a way to get address string (without length) from IPAddress?

### ISSUE THREAD

**Issue by simPod** [seancfoley/IPAddress#98]
`new IPAddressString("0.0.0.0/0").getAddress()`

How can I get `0.0.0.0` from `IPAddress`?

**Comment by seancfoley** [comment]
Use [getHostAddress](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddressString.html#getHostAddress--) or [toHostAddress](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddressString.html#toHostAddress--)

**Comment by seancfoley** [comment]
[Other options are to use toZeroHost or getLower ](https://github.com/seancfoley/IPAddress/wiki/Code-Examples-1:-Creating,-Parsing,-Extracting-Address-Subnet-Info#to-get-just-the-single-address)and on the result call  [withoutPrefixLength](https://seancfoley.github.io/IPAddress/IPAddress/apidocs/inet/ipaddr/IPAddress.html#withoutPrefixLength--)
